plugins {
    id 'org.springframework.boot' version '3.2.3'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
}

dependencies {
    implementation project(':common')

    // 引入 SchemConvert
    // 注意：这里的 group:name 必须匹配子模块定义的 group 和其文件夹名（或 rootProject.name）
    implementation 'pitheguy.schemconvert:SchemConvert'

    // Source: https://mvnrepository.com/artifact/org.projectlombok/lombok
    // lombok，编译有效，打包无效
    compileOnly 'org.projectlombok:lombok'
    // gradle 5.0以上版本注解处理不再compile classpath，需要增加 annotation processor path
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // Default to H2 for easy startup, can be changed to MySQL/Postgres
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.xerial:sqlite-jdbc:3.45.1.0'
    runtimeOnly 'org.postgresql:postgresql'
    // Spring Boot 3+ Hibernate compatibility for SQLite needs this dialect or careful config
    implementation 'org.hibernate.orm:hibernate-community-dialects:6.4.4.Final'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Source: https://mvnrepository.com/artifact/com.github.usefulness/webp-imageio
    implementation group: 'com.github.usefulness', name: 'webp-imageio', version: '0.10.2'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    archiveFileName = 'backend.jar'
}
