update:
  idle-blocks:
    - "minecraft:air"
    - "minecraft:cave_air"
    - "minecraft:void_air"
    - "minecraft:water"
    - "minecraft:lava"
    - "minecraft:light"

emptyBlocks:
  - "AIR"
  - "CAVE_AIR"
  - "VOID_AIR"
  - "WATER"
  - "LAVA"
  - "GRASS"
  - "TALL_GRASS"
  - "SEAGRASS"
  - "TALL_SEAGRASS"
  - "FERN"
  - "LARGE_FERN"
  - "DEAD_BUSH"
  - "SNOW"
