// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNeCompProductLog = "ne_comp_product_logs"

// NeCompProductLog mapped from table <ne_comp_product_logs>
type NeCompProductLog struct {
	ID                   int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NeUserLogID          *int64  `gorm:"column:ne_user_log_id" json:"ne_user_log_id"`
	ApplyReviewTime      *string `gorm:"column:apply_review_time" json:"apply_review_time"`
	ApplyReviewTimeMs    *int64  `gorm:"column:apply_review_time_ms" json:"apply_review_time_ms"`
	CanManageServer      *bool   `gorm:"column:can_manage_server" json:"can_manage_server"`
	CanSilentOnline      *bool   `gorm:"column:can_silent_online" json:"can_silent_online"`
	CreateTime           *string `gorm:"column:create_time" json:"create_time"`
	CreateTimeMs         *int64  `gorm:"column:create_time_ms" json:"create_time_ms"`
	Discount             *string `gorm:"column:discount" json:"discount"`
	ExemptPerfReviewNum  *int32  `gorm:"column:exempt_perf_review_num" json:"exempt_perf_review_num"`
	InterceptFields      *string `gorm:"column:intercept_fields" json:"intercept_fields"`
	IsEa                 *int32  `gorm:"column:is_ea" json:"is_ea"`
	IsOriginal           *bool   `gorm:"column:is_original" json:"is_original"`
	IsSilentOnline       *bool   `gorm:"column:is_silent_online" json:"is_silent_online"`
	IsSync               *bool   `gorm:"column:is_sync" json:"is_sync"`
	IsTestServer         *bool   `gorm:"column:is_test_server" json:"is_test_server"`
	ItemID               *string `gorm:"column:item_id" json:"item_id"`
	ItemIDInt            *int64  `gorm:"column:item_id_int" json:"item_id_int"`
	ItemName             *string `gorm:"column:item_name" json:"item_name"`
	LobbyConfigOpLog     *string `gorm:"column:lobby_config_op_log" json:"lobby_config_op_log"`
	LobbySortKey         *string `gorm:"column:lobby_sort_key" json:"lobby_sort_key"`
	OnlineTime           *string `gorm:"column:online_time" json:"online_time"`
	OnlineTimeMs         *int64  `gorm:"column:online_time_ms" json:"online_time_ms"`
	OriWeakOffline       *bool   `gorm:"column:ori_weak_offline" json:"ori_weak_offline"`
	OriWeakOfflineReason *string `gorm:"column:ori_weak_offline_reason" json:"ori_weak_offline_reason"`
	PlayPlanExpireMonth  *int32  `gorm:"column:play_plan_expire_month" json:"play_plan_expire_month"`
	PriType              *int32  `gorm:"column:pri_type" json:"pri_type"`
	Price                *int32  `gorm:"column:price" json:"price"`
	PriceRank            *int32  `gorm:"column:price_rank" json:"price_rank"`
	PriceType            *string `gorm:"column:price_type" json:"price_type"`
	QueuePosition        *int32  `gorm:"column:queue_position" json:"queue_position"`
	RatingLevel          *int32  `gorm:"column:rating_level" json:"rating_level"`
	RelateItemID         *string `gorm:"column:relate_item_id" json:"relate_item_id"`
	Remindable           *bool   `gorm:"column:remindable" json:"remindable"`
	Status               *string `gorm:"column:status" json:"status"`
	SyncPcFlag           *bool   `gorm:"column:sync_pc_flag" json:"sync_pc_flag"`
	UrgentStatus         *int32  `gorm:"column:urgent_status" json:"urgent_status"`
	WeakOffline          *bool   `gorm:"column:weak_offline" json:"weak_offline"`
	WeakOfflineReason    *string `gorm:"column:weak_offline_reason" json:"weak_offline_reason"`
}

// TableName NeCompProductLog's table name
func (*NeCompProductLog) TableName() string {
	return TableNameNeCompProductLog
}
