// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNeLog = "ne_logs"

// NeLog mapped from table <ne_logs>
type NeLog struct {
	ID               int64  `gorm:"column:id;primaryKey" json:"id"`
	CreateTimeMs     int64  `gorm:"column:create_time_ms;not null" json:"create_time_ms"`
	StartCrawlTimeMs *int64 `gorm:"column:start_crawl_time_ms" json:"start_crawl_time_ms"`
	EndCrawlTimeMs   *int64 `gorm:"column:end_crawl_time_ms" json:"end_crawl_time_ms"`
}

// TableName NeLog's table name
func (*NeLog) TableName() string {
	return TableNameNeLog
}
