// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNePeProductFeedbackLog = "ne_pe_product_feedback_logs"

// NePeProductFeedbackLog mapped from table <ne_pe_product_feedback_logs>
type NePeProductFeedbackLog struct {
	ID              int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FeedbackID      *string `gorm:"column:feedback_id" json:"feedback_id"`
	CommitNickname  *string `gorm:"column:commit_nickname" json:"commit_nickname"`
	CommitUID       *string `gorm:"column:commit_uid" json:"commit_uid"`
	CommitUIDInt    *int64  `gorm:"column:commit_uid_int" json:"commit_uid_int"`
	Content         *string `gorm:"column:content" json:"content"`
	CreateTimeMs    *int64  `gorm:"column:create_time_ms" json:"create_time_ms"`
	FeedbackLogFile *string `gorm:"column:feedback_log_file" json:"feedback_log_file"`
	ForbidReply     *bool   `gorm:"column:forbid_reply" json:"forbid_reply"`
	HaveLogFile     *bool   `gorm:"column:have_log_file" json:"have_log_file"`
	Iid             *string `gorm:"column:iid" json:"iid"`
	IidInt          *int64  `gorm:"column:iid_int" json:"iid_int"`
	PicList         *string `gorm:"column:pic_list" json:"pic_list"`
	ResName         *string `gorm:"column:res_name" json:"res_name"`
	Type            *string `gorm:"column:type" json:"type"`
}

// TableName NePeProductFeedbackLog's table name
func (*NePeProductFeedbackLog) TableName() string {
	return TableNameNePeProductFeedbackLog
}
