// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNePeProductOrderLog = "ne_pe_product_order_logs"

// NePeProductOrderLog mapped from table <ne_pe_product_order_logs>
type NePeProductOrderLog struct {
	ID               int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NePeProductLogID *int64  `gorm:"column:ne_pe_product_log_id" json:"ne_pe_product_log_id"`
	AppOrderID       *string `gorm:"column:app_order_id" json:"app_order_id"`
	AppOrderIDInt    *int64  `gorm:"column:app_order_id_int" json:"app_order_id_int"`
	AppUID           *string `gorm:"column:app_uid" json:"app_uid"`
	AppUIDInt        *int64  `gorm:"column:app_uid_int" json:"app_uid_int"`
	Discount         *string `gorm:"column:discount" json:"discount"`
	OfficialChannel  *int32  `gorm:"column:official_channel" json:"official_channel"`
	Point            *int32  `gorm:"column:point" json:"point"`
	PointType        *string `gorm:"column:point_type" json:"point_type"`
	Price            *int32  `gorm:"column:price" json:"price"`
	PriceType        *string `gorm:"column:price_type" json:"price_type"`
	ProductName      *string `gorm:"column:product_name" json:"product_name"`
	PurchaseLimit    *int32  `gorm:"column:purchase_limit" json:"purchase_limit"`
	RefundStatus     *string `gorm:"column:refund_status" json:"refund_status"`
	ShipTime         *string `gorm:"column:ship_time" json:"ship_time"`
	ShipTimeMs       *int64  `gorm:"column:ship_time_ms" json:"ship_time_ms"`
}

// TableName NePeProductOrderLog's table name
func (*NePeProductOrderLog) TableName() string {
	return TableNameNePeProductOrderLog
}
