// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNePeProductStatLog = "ne_pe_product_stat_logs"

// NePeProductStatLog mapped from table <ne_pe_product_stat_logs>
type NePeProductStatLog struct {
	ID                   int64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NePeProductLogID     *int64   `gorm:"column:ne_pe_product_log_id" json:"ne_pe_product_log_id"`
	Dau                  *int32   `gorm:"column:dau" json:"dau"`
	AvgFirstTypeBuy      *float64 `gorm:"column:avg_first_type_buy" json:"avg_first_type_buy"`
	AvgFirstTypeDiamond  *float64 `gorm:"column:avg_first_type_diamond" json:"avg_first_type_diamond"`
	AvgFirstTypeFocus    *float64 `gorm:"column:avg_first_type_focus" json:"avg_first_type_focus"`
	AvgFirstTypeRolePlay *float64 `gorm:"column:avg_first_type_role_play" json:"avg_first_type_role_play"`
	AvgPlaytime          *float64 `gorm:"column:avg_playtime" json:"avg_playtime"`
	AvgTotalFirstTypeBuy *float64 `gorm:"column:avg_total_first_type_buy" json:"avg_total_first_type_buy"`
	CntBuy               *int32   `gorm:"column:cnt_buy" json:"cnt_buy"`
	DateID               *string  `gorm:"column:date_id" json:"date_id"`
	DateMs               *int64   `gorm:"column:date_ms" json:"date_ms"`
	Diamond              *int32   `gorm:"column:diamond" json:"diamond"`
	DownloadNum          *int32   `gorm:"column:download_num" json:"download_num"`
	FirstTypeAvgRoleTime *float64 `gorm:"column:first_type_avg_role_time" json:"first_type_avg_role_time"`
	FocusCnt             *int32   `gorm:"column:focus_cnt" json:"focus_cnt"`
	Iid                  *string  `gorm:"column:iid" json:"iid"`
	IidInt               *int64   `gorm:"column:iid_int" json:"iid_int"`
	PassAvgRoleTimeRatio *float64 `gorm:"column:pass_avg_role_time_ratio" json:"pass_avg_role_time_ratio"`
	PassBuyCntRatio      *float64 `gorm:"column:pass_buy_cnt_ratio" json:"pass_buy_cnt_ratio"`
	PassCntRolePlayRatio *float64 `gorm:"column:pass_cnt_role_play_ratio" json:"pass_cnt_role_play_ratio"`
	PassFocusCntRatio    *float64 `gorm:"column:pass_focus_cnt_ratio" json:"pass_focus_cnt_ratio"`
	PassPayDiamondRatio  *float64 `gorm:"column:pass_pay_diamond_ratio" json:"pass_pay_diamond_ratio"`
	Platform             *string  `gorm:"column:platform" json:"platform"`
	Points               *int32   `gorm:"column:points" json:"points"`
	RefundRate           *float64 `gorm:"column:refund_rate" json:"refund_rate"`
	ResName              *string  `gorm:"column:res_name" json:"res_name"`
	StarAdjusted         *float64 `gorm:"column:star_adjusted" json:"star_adjusted"`
	UploadTime           *string  `gorm:"column:upload_time" json:"upload_time"`
	UploadTimeMs         *int64   `gorm:"column:upload_time_ms" json:"upload_time_ms"`
}

// TableName NePeProductStatLog's table name
func (*NePeProductStatLog) TableName() string {
	return TableNameNePeProductStatLog
}
