// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNePeProductCommentLog = "ne_pe_product_comment_logs"

// NePeProductCommentLog mapped from table <ne_pe_product_comment_logs>
type NePeProductCommentLog struct {
	ID              int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentID       *string `gorm:"column:comment_id" json:"comment_id"`
	CommentState    *string `gorm:"column:comment_state" json:"comment_state"`
	CommentTag      *string `gorm:"column:comment_tag" json:"comment_tag"`
	CommentedNum    *string `gorm:"column:commented_num" json:"commented_num"`
	CommentedNumInt *int64  `gorm:"column:commented_num_int" json:"commented_num_int"`
	GoodNum         *string `gorm:"column:good_num" json:"good_num"`
	GoodNumInt      *int64  `gorm:"column:good_num_int" json:"good_num_int"`
	Iid             *string `gorm:"column:iid" json:"iid"`
	IidInt          *int64  `gorm:"column:iid_int" json:"iid_int"`
	MasterID        *string `gorm:"column:master_id" json:"master_id"`
	MasterIDInt     *int64  `gorm:"column:master_id_int" json:"master_id_int"`
	Nickname        *string `gorm:"column:nickname" json:"nickname"`
	PublishTime     *string `gorm:"column:publish_time" json:"publish_time"`
	PublishTimeMs   *int64  `gorm:"column:publish_time_ms" json:"publish_time_ms"`
	ReplyID         *string `gorm:"column:reply_id" json:"reply_id"`
	ReplyIDInt      *int64  `gorm:"column:reply_id_int" json:"reply_id_int"`
	ResName         *string `gorm:"column:res_name" json:"res_name"`
	Stars           *string `gorm:"column:stars" json:"stars"`
	StarsInt        *int64  `gorm:"column:stars_int" json:"stars_int"`
	UID             *string `gorm:"column:uid" json:"uid"`
	UIDInt          *int64  `gorm:"column:uid_int" json:"uid_int"`
	UserComment     *string `gorm:"column:user_comment" json:"user_comment"`
}

// TableName NePeProductCommentLog's table name
func (*NePeProductCommentLog) TableName() string {
	return TableNameNePeProductCommentLog
}
