// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNeUserLog = "ne_user_logs"

// NeUserLog mapped from table <ne_user_logs>
type NeUserLog struct {
	ID                           int64   `gorm:"column:id;primaryKey" json:"id"`
	NeLogID                      *int64  `gorm:"column:ne_log_id" json:"ne_log_id"`
	UserID                       string  `gorm:"column:user_id;not null" json:"user_id"`
	PeProductsPayload            *string `gorm:"column:pe_products_payload" json:"pe_products_payload"`
	PeProductCommentLogsPayload  *string `gorm:"column:pe_product_comment_logs_payload" json:"pe_product_comment_logs_payload"`
	PeProductFeedbackLogsPayload *string `gorm:"column:pe_product_feedback_logs_payload" json:"pe_product_feedback_logs_payload"`
	CompProductLogsPayload       *string `gorm:"column:comp_product_logs_payload" json:"comp_product_logs_payload"`
}

// TableName NeUserLog's table name
func (*NeUserLog) TableName() string {
	return TableNameNeUserLog
}
