// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	NeCompProductLog       *neCompProductLog
	NeLog                  *neLog
	NePeProductCommentLog  *nePeProductCommentLog
	NePeProductFeedbackLog *nePeProductFeedbackLog
	NePeProductLog         *nePeProductLog
	NePeProductOrderLog    *nePeProductOrderLog
	NePeProductStatLog     *nePeProductStatLog
	NeUserLog              *neUserLog
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	NeCompProductLog = &Q.NeCompProductLog
	NeLog = &Q.NeLog
	NePeProductCommentLog = &Q.NePeProductCommentLog
	NePeProductFeedbackLog = &Q.NePeProductFeedbackLog
	NePeProductLog = &Q.NePeProductLog
	NePeProductOrderLog = &Q.NePeProductOrderLog
	NePeProductStatLog = &Q.NePeProductStatLog
	NeUserLog = &Q.NeUserLog
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		NeCompProductLog:       newNeCompProductLog(db, opts...),
		NeLog:                  newNeLog(db, opts...),
		NePeProductCommentLog:  newNePeProductCommentLog(db, opts...),
		NePeProductFeedbackLog: newNePeProductFeedbackLog(db, opts...),
		NePeProductLog:         newNePeProductLog(db, opts...),
		NePeProductOrderLog:    newNePeProductOrderLog(db, opts...),
		NePeProductStatLog:     newNePeProductStatLog(db, opts...),
		NeUserLog:              newNeUserLog(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	NeCompProductLog       neCompProductLog
	NeLog                  neLog
	NePeProductCommentLog  nePeProductCommentLog
	NePeProductFeedbackLog nePeProductFeedbackLog
	NePeProductLog         nePeProductLog
	NePeProductOrderLog    nePeProductOrderLog
	NePeProductStatLog     nePeProductStatLog
	NeUserLog              neUserLog
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		NeCompProductLog:       q.NeCompProductLog.clone(db),
		NeLog:                  q.NeLog.clone(db),
		NePeProductCommentLog:  q.NePeProductCommentLog.clone(db),
		NePeProductFeedbackLog: q.NePeProductFeedbackLog.clone(db),
		NePeProductLog:         q.NePeProductLog.clone(db),
		NePeProductOrderLog:    q.NePeProductOrderLog.clone(db),
		NePeProductStatLog:     q.NePeProductStatLog.clone(db),
		NeUserLog:              q.NeUserLog.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		NeCompProductLog:       q.NeCompProductLog.replaceDB(db),
		NeLog:                  q.NeLog.replaceDB(db),
		NePeProductCommentLog:  q.NePeProductCommentLog.replaceDB(db),
		NePeProductFeedbackLog: q.NePeProductFeedbackLog.replaceDB(db),
		NePeProductLog:         q.NePeProductLog.replaceDB(db),
		NePeProductOrderLog:    q.NePeProductOrderLog.replaceDB(db),
		NePeProductStatLog:     q.NePeProductStatLog.replaceDB(db),
		NeUserLog:              q.NeUserLog.replaceDB(db),
	}
}

type queryCtx struct {
	NeCompProductLog       INeCompProductLogDo
	NeLog                  INeLogDo
	NePeProductCommentLog  INePeProductCommentLogDo
	NePeProductFeedbackLog INePeProductFeedbackLogDo
	NePeProductLog         INePeProductLogDo
	NePeProductOrderLog    INePeProductOrderLogDo
	NePeProductStatLog     INePeProductStatLogDo
	NeUserLog              INeUserLogDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		NeCompProductLog:       q.NeCompProductLog.WithContext(ctx),
		NeLog:                  q.NeLog.WithContext(ctx),
		NePeProductCommentLog:  q.NePeProductCommentLog.WithContext(ctx),
		NePeProductFeedbackLog: q.NePeProductFeedbackLog.WithContext(ctx),
		NePeProductLog:         q.NePeProductLog.WithContext(ctx),
		NePeProductOrderLog:    q.NePeProductOrderLog.WithContext(ctx),
		NePeProductStatLog:     q.NePeProductStatLog.WithContext(ctx),
		NeUserLog:              q.NeUserLog.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
