// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNeCompProductLog(db *gorm.DB, opts ...gen.DOOption) neCompProductLog {
	_neCompProductLog := neCompProductLog{}

	_neCompProductLog.neCompProductLogDo.UseDB(db, opts...)
	_neCompProductLog.neCompProductLogDo.UseModel(&model.NeCompProductLog{})

	tableName := _neCompProductLog.neCompProductLogDo.TableName()
	_neCompProductLog.ALL = field.NewAsterisk(tableName)
	_neCompProductLog.ID = field.NewInt64(tableName, "id")
	_neCompProductLog.NeUserLogID = field.NewInt64(tableName, "ne_user_log_id")
	_neCompProductLog.ApplyReviewTime = field.NewString(tableName, "apply_review_time")
	_neCompProductLog.ApplyReviewTimeMs = field.NewInt64(tableName, "apply_review_time_ms")
	_neCompProductLog.CanManageServer = field.NewBool(tableName, "can_manage_server")
	_neCompProductLog.CanSilentOnline = field.NewBool(tableName, "can_silent_online")
	_neCompProductLog.CreateTime = field.NewString(tableName, "create_time")
	_neCompProductLog.CreateTimeMs = field.NewInt64(tableName, "create_time_ms")
	_neCompProductLog.Discount = field.NewString(tableName, "discount")
	_neCompProductLog.ExemptPerfReviewNum = field.NewInt32(tableName, "exempt_perf_review_num")
	_neCompProductLog.InterceptFields = field.NewString(tableName, "intercept_fields")
	_neCompProductLog.IsEa = field.NewInt32(tableName, "is_ea")
	_neCompProductLog.IsOriginal = field.NewBool(tableName, "is_original")
	_neCompProductLog.IsSilentOnline = field.NewBool(tableName, "is_silent_online")
	_neCompProductLog.IsSync = field.NewBool(tableName, "is_sync")
	_neCompProductLog.IsTestServer = field.NewBool(tableName, "is_test_server")
	_neCompProductLog.ItemID = field.NewString(tableName, "item_id")
	_neCompProductLog.ItemIDInt = field.NewInt64(tableName, "item_id_int")
	_neCompProductLog.ItemName = field.NewString(tableName, "item_name")
	_neCompProductLog.LobbyConfigOpLog = field.NewString(tableName, "lobby_config_op_log")
	_neCompProductLog.LobbySortKey = field.NewString(tableName, "lobby_sort_key")
	_neCompProductLog.OnlineTime = field.NewString(tableName, "online_time")
	_neCompProductLog.OnlineTimeMs = field.NewInt64(tableName, "online_time_ms")
	_neCompProductLog.OriWeakOffline = field.NewBool(tableName, "ori_weak_offline")
	_neCompProductLog.OriWeakOfflineReason = field.NewString(tableName, "ori_weak_offline_reason")
	_neCompProductLog.PlayPlanExpireMonth = field.NewInt32(tableName, "play_plan_expire_month")
	_neCompProductLog.PriType = field.NewInt32(tableName, "pri_type")
	_neCompProductLog.Price = field.NewInt32(tableName, "price")
	_neCompProductLog.PriceRank = field.NewInt32(tableName, "price_rank")
	_neCompProductLog.PriceType = field.NewString(tableName, "price_type")
	_neCompProductLog.QueuePosition = field.NewInt32(tableName, "queue_position")
	_neCompProductLog.RatingLevel = field.NewInt32(tableName, "rating_level")
	_neCompProductLog.RelateItemID = field.NewString(tableName, "relate_item_id")
	_neCompProductLog.Remindable = field.NewBool(tableName, "remindable")
	_neCompProductLog.Status = field.NewString(tableName, "status")
	_neCompProductLog.SyncPcFlag = field.NewBool(tableName, "sync_pc_flag")
	_neCompProductLog.UrgentStatus = field.NewInt32(tableName, "urgent_status")
	_neCompProductLog.WeakOffline = field.NewBool(tableName, "weak_offline")
	_neCompProductLog.WeakOfflineReason = field.NewString(tableName, "weak_offline_reason")

	_neCompProductLog.fillFieldMap()

	return _neCompProductLog
}

type neCompProductLog struct {
	neCompProductLogDo neCompProductLogDo

	ALL                  field.Asterisk
	ID                   field.Int64
	NeUserLogID          field.Int64
	ApplyReviewTime      field.String
	ApplyReviewTimeMs    field.Int64
	CanManageServer      field.Bool
	CanSilentOnline      field.Bool
	CreateTime           field.String
	CreateTimeMs         field.Int64
	Discount             field.String
	ExemptPerfReviewNum  field.Int32
	InterceptFields      field.String
	IsEa                 field.Int32
	IsOriginal           field.Bool
	IsSilentOnline       field.Bool
	IsSync               field.Bool
	IsTestServer         field.Bool
	ItemID               field.String
	ItemIDInt            field.Int64
	ItemName             field.String
	LobbyConfigOpLog     field.String
	LobbySortKey         field.String
	OnlineTime           field.String
	OnlineTimeMs         field.Int64
	OriWeakOffline       field.Bool
	OriWeakOfflineReason field.String
	PlayPlanExpireMonth  field.Int32
	PriType              field.Int32
	Price                field.Int32
	PriceRank            field.Int32
	PriceType            field.String
	QueuePosition        field.Int32
	RatingLevel          field.Int32
	RelateItemID         field.String
	Remindable           field.Bool
	Status               field.String
	SyncPcFlag           field.Bool
	UrgentStatus         field.Int32
	WeakOffline          field.Bool
	WeakOfflineReason    field.String

	fieldMap map[string]field.Expr
}

func (n neCompProductLog) Table(newTableName string) *neCompProductLog {
	n.neCompProductLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n neCompProductLog) As(alias string) *neCompProductLog {
	n.neCompProductLogDo.DO = *(n.neCompProductLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *neCompProductLog) updateTableName(table string) *neCompProductLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NeUserLogID = field.NewInt64(table, "ne_user_log_id")
	n.ApplyReviewTime = field.NewString(table, "apply_review_time")
	n.ApplyReviewTimeMs = field.NewInt64(table, "apply_review_time_ms")
	n.CanManageServer = field.NewBool(table, "can_manage_server")
	n.CanSilentOnline = field.NewBool(table, "can_silent_online")
	n.CreateTime = field.NewString(table, "create_time")
	n.CreateTimeMs = field.NewInt64(table, "create_time_ms")
	n.Discount = field.NewString(table, "discount")
	n.ExemptPerfReviewNum = field.NewInt32(table, "exempt_perf_review_num")
	n.InterceptFields = field.NewString(table, "intercept_fields")
	n.IsEa = field.NewInt32(table, "is_ea")
	n.IsOriginal = field.NewBool(table, "is_original")
	n.IsSilentOnline = field.NewBool(table, "is_silent_online")
	n.IsSync = field.NewBool(table, "is_sync")
	n.IsTestServer = field.NewBool(table, "is_test_server")
	n.ItemID = field.NewString(table, "item_id")
	n.ItemIDInt = field.NewInt64(table, "item_id_int")
	n.ItemName = field.NewString(table, "item_name")
	n.LobbyConfigOpLog = field.NewString(table, "lobby_config_op_log")
	n.LobbySortKey = field.NewString(table, "lobby_sort_key")
	n.OnlineTime = field.NewString(table, "online_time")
	n.OnlineTimeMs = field.NewInt64(table, "online_time_ms")
	n.OriWeakOffline = field.NewBool(table, "ori_weak_offline")
	n.OriWeakOfflineReason = field.NewString(table, "ori_weak_offline_reason")
	n.PlayPlanExpireMonth = field.NewInt32(table, "play_plan_expire_month")
	n.PriType = field.NewInt32(table, "pri_type")
	n.Price = field.NewInt32(table, "price")
	n.PriceRank = field.NewInt32(table, "price_rank")
	n.PriceType = field.NewString(table, "price_type")
	n.QueuePosition = field.NewInt32(table, "queue_position")
	n.RatingLevel = field.NewInt32(table, "rating_level")
	n.RelateItemID = field.NewString(table, "relate_item_id")
	n.Remindable = field.NewBool(table, "remindable")
	n.Status = field.NewString(table, "status")
	n.SyncPcFlag = field.NewBool(table, "sync_pc_flag")
	n.UrgentStatus = field.NewInt32(table, "urgent_status")
	n.WeakOffline = field.NewBool(table, "weak_offline")
	n.WeakOfflineReason = field.NewString(table, "weak_offline_reason")

	n.fillFieldMap()

	return n
}

func (n *neCompProductLog) WithContext(ctx context.Context) INeCompProductLogDo {
	return n.neCompProductLogDo.WithContext(ctx)
}

func (n neCompProductLog) TableName() string { return n.neCompProductLogDo.TableName() }

func (n neCompProductLog) Alias() string { return n.neCompProductLogDo.Alias() }

func (n neCompProductLog) Columns(cols ...field.Expr) gen.Columns {
	return n.neCompProductLogDo.Columns(cols...)
}

func (n *neCompProductLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *neCompProductLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 39)
	n.fieldMap["id"] = n.ID
	n.fieldMap["ne_user_log_id"] = n.NeUserLogID
	n.fieldMap["apply_review_time"] = n.ApplyReviewTime
	n.fieldMap["apply_review_time_ms"] = n.ApplyReviewTimeMs
	n.fieldMap["can_manage_server"] = n.CanManageServer
	n.fieldMap["can_silent_online"] = n.CanSilentOnline
	n.fieldMap["create_time"] = n.CreateTime
	n.fieldMap["create_time_ms"] = n.CreateTimeMs
	n.fieldMap["discount"] = n.Discount
	n.fieldMap["exempt_perf_review_num"] = n.ExemptPerfReviewNum
	n.fieldMap["intercept_fields"] = n.InterceptFields
	n.fieldMap["is_ea"] = n.IsEa
	n.fieldMap["is_original"] = n.IsOriginal
	n.fieldMap["is_silent_online"] = n.IsSilentOnline
	n.fieldMap["is_sync"] = n.IsSync
	n.fieldMap["is_test_server"] = n.IsTestServer
	n.fieldMap["item_id"] = n.ItemID
	n.fieldMap["item_id_int"] = n.ItemIDInt
	n.fieldMap["item_name"] = n.ItemName
	n.fieldMap["lobby_config_op_log"] = n.LobbyConfigOpLog
	n.fieldMap["lobby_sort_key"] = n.LobbySortKey
	n.fieldMap["online_time"] = n.OnlineTime
	n.fieldMap["online_time_ms"] = n.OnlineTimeMs
	n.fieldMap["ori_weak_offline"] = n.OriWeakOffline
	n.fieldMap["ori_weak_offline_reason"] = n.OriWeakOfflineReason
	n.fieldMap["play_plan_expire_month"] = n.PlayPlanExpireMonth
	n.fieldMap["pri_type"] = n.PriType
	n.fieldMap["price"] = n.Price
	n.fieldMap["price_rank"] = n.PriceRank
	n.fieldMap["price_type"] = n.PriceType
	n.fieldMap["queue_position"] = n.QueuePosition
	n.fieldMap["rating_level"] = n.RatingLevel
	n.fieldMap["relate_item_id"] = n.RelateItemID
	n.fieldMap["remindable"] = n.Remindable
	n.fieldMap["status"] = n.Status
	n.fieldMap["sync_pc_flag"] = n.SyncPcFlag
	n.fieldMap["urgent_status"] = n.UrgentStatus
	n.fieldMap["weak_offline"] = n.WeakOffline
	n.fieldMap["weak_offline_reason"] = n.WeakOfflineReason
}

func (n neCompProductLog) clone(db *gorm.DB) neCompProductLog {
	n.neCompProductLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n neCompProductLog) replaceDB(db *gorm.DB) neCompProductLog {
	n.neCompProductLogDo.ReplaceDB(db)
	return n
}

type neCompProductLogDo struct{ gen.DO }

type INeCompProductLogDo interface {
	gen.SubQuery
	Debug() INeCompProductLogDo
	WithContext(ctx context.Context) INeCompProductLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INeCompProductLogDo
	WriteDB() INeCompProductLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INeCompProductLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INeCompProductLogDo
	Not(conds ...gen.Condition) INeCompProductLogDo
	Or(conds ...gen.Condition) INeCompProductLogDo
	Select(conds ...field.Expr) INeCompProductLogDo
	Where(conds ...gen.Condition) INeCompProductLogDo
	Order(conds ...field.Expr) INeCompProductLogDo
	Distinct(cols ...field.Expr) INeCompProductLogDo
	Omit(cols ...field.Expr) INeCompProductLogDo
	Join(table schema.Tabler, on ...field.Expr) INeCompProductLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INeCompProductLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INeCompProductLogDo
	Group(cols ...field.Expr) INeCompProductLogDo
	Having(conds ...gen.Condition) INeCompProductLogDo
	Limit(limit int) INeCompProductLogDo
	Offset(offset int) INeCompProductLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INeCompProductLogDo
	Unscoped() INeCompProductLogDo
	Create(values ...*model.NeCompProductLog) error
	CreateInBatches(values []*model.NeCompProductLog, batchSize int) error
	Save(values ...*model.NeCompProductLog) error
	First() (*model.NeCompProductLog, error)
	Take() (*model.NeCompProductLog, error)
	Last() (*model.NeCompProductLog, error)
	Find() ([]*model.NeCompProductLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NeCompProductLog, err error)
	FindInBatches(result *[]*model.NeCompProductLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NeCompProductLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INeCompProductLogDo
	Assign(attrs ...field.AssignExpr) INeCompProductLogDo
	Joins(fields ...field.RelationField) INeCompProductLogDo
	Preload(fields ...field.RelationField) INeCompProductLogDo
	FirstOrInit() (*model.NeCompProductLog, error)
	FirstOrCreate() (*model.NeCompProductLog, error)
	FindByPage(offset int, limit int) (result []*model.NeCompProductLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INeCompProductLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n neCompProductLogDo) Debug() INeCompProductLogDo {
	return n.withDO(n.DO.Debug())
}

func (n neCompProductLogDo) WithContext(ctx context.Context) INeCompProductLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n neCompProductLogDo) ReadDB() INeCompProductLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n neCompProductLogDo) WriteDB() INeCompProductLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n neCompProductLogDo) Session(config *gorm.Session) INeCompProductLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n neCompProductLogDo) Clauses(conds ...clause.Expression) INeCompProductLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n neCompProductLogDo) Returning(value interface{}, columns ...string) INeCompProductLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n neCompProductLogDo) Not(conds ...gen.Condition) INeCompProductLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n neCompProductLogDo) Or(conds ...gen.Condition) INeCompProductLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n neCompProductLogDo) Select(conds ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n neCompProductLogDo) Where(conds ...gen.Condition) INeCompProductLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n neCompProductLogDo) Order(conds ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n neCompProductLogDo) Distinct(cols ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n neCompProductLogDo) Omit(cols ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n neCompProductLogDo) Join(table schema.Tabler, on ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n neCompProductLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n neCompProductLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n neCompProductLogDo) Group(cols ...field.Expr) INeCompProductLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n neCompProductLogDo) Having(conds ...gen.Condition) INeCompProductLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n neCompProductLogDo) Limit(limit int) INeCompProductLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n neCompProductLogDo) Offset(offset int) INeCompProductLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n neCompProductLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INeCompProductLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n neCompProductLogDo) Unscoped() INeCompProductLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n neCompProductLogDo) Create(values ...*model.NeCompProductLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n neCompProductLogDo) CreateInBatches(values []*model.NeCompProductLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n neCompProductLogDo) Save(values ...*model.NeCompProductLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n neCompProductLogDo) First() (*model.NeCompProductLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeCompProductLog), nil
	}
}

func (n neCompProductLogDo) Take() (*model.NeCompProductLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeCompProductLog), nil
	}
}

func (n neCompProductLogDo) Last() (*model.NeCompProductLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeCompProductLog), nil
	}
}

func (n neCompProductLogDo) Find() ([]*model.NeCompProductLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NeCompProductLog), err
}

func (n neCompProductLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NeCompProductLog, err error) {
	buf := make([]*model.NeCompProductLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n neCompProductLogDo) FindInBatches(result *[]*model.NeCompProductLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n neCompProductLogDo) Attrs(attrs ...field.AssignExpr) INeCompProductLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n neCompProductLogDo) Assign(attrs ...field.AssignExpr) INeCompProductLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n neCompProductLogDo) Joins(fields ...field.RelationField) INeCompProductLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n neCompProductLogDo) Preload(fields ...field.RelationField) INeCompProductLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n neCompProductLogDo) FirstOrInit() (*model.NeCompProductLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeCompProductLog), nil
	}
}

func (n neCompProductLogDo) FirstOrCreate() (*model.NeCompProductLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeCompProductLog), nil
	}
}

func (n neCompProductLogDo) FindByPage(offset int, limit int) (result []*model.NeCompProductLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n neCompProductLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n neCompProductLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n neCompProductLogDo) Delete(models ...*model.NeCompProductLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *neCompProductLogDo) withDO(do gen.Dao) *neCompProductLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
