// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNeLog(db *gorm.DB, opts ...gen.DOOption) neLog {
	_neLog := neLog{}

	_neLog.neLogDo.UseDB(db, opts...)
	_neLog.neLogDo.UseModel(&model.NeLog{})

	tableName := _neLog.neLogDo.TableName()
	_neLog.ALL = field.NewAsterisk(tableName)
	_neLog.ID = field.NewInt64(tableName, "id")
	_neLog.CreateTimeMs = field.NewInt64(tableName, "create_time_ms")
	_neLog.StartCrawlTimeMs = field.NewInt64(tableName, "start_crawl_time_ms")
	_neLog.EndCrawlTimeMs = field.NewInt64(tableName, "end_crawl_time_ms")

	_neLog.fillFieldMap()

	return _neLog
}

type neLog struct {
	neLogDo neLogDo

	ALL              field.Asterisk
	ID               field.Int64
	CreateTimeMs     field.Int64
	StartCrawlTimeMs field.Int64
	EndCrawlTimeMs   field.Int64

	fieldMap map[string]field.Expr
}

func (n neLog) Table(newTableName string) *neLog {
	n.neLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n neLog) As(alias string) *neLog {
	n.neLogDo.DO = *(n.neLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *neLog) updateTableName(table string) *neLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.CreateTimeMs = field.NewInt64(table, "create_time_ms")
	n.StartCrawlTimeMs = field.NewInt64(table, "start_crawl_time_ms")
	n.EndCrawlTimeMs = field.NewInt64(table, "end_crawl_time_ms")

	n.fillFieldMap()

	return n
}

func (n *neLog) WithContext(ctx context.Context) INeLogDo { return n.neLogDo.WithContext(ctx) }

func (n neLog) TableName() string { return n.neLogDo.TableName() }

func (n neLog) Alias() string { return n.neLogDo.Alias() }

func (n neLog) Columns(cols ...field.Expr) gen.Columns { return n.neLogDo.Columns(cols...) }

func (n *neLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *neLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 4)
	n.fieldMap["id"] = n.ID
	n.fieldMap["create_time_ms"] = n.CreateTimeMs
	n.fieldMap["start_crawl_time_ms"] = n.StartCrawlTimeMs
	n.fieldMap["end_crawl_time_ms"] = n.EndCrawlTimeMs
}

func (n neLog) clone(db *gorm.DB) neLog {
	n.neLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n neLog) replaceDB(db *gorm.DB) neLog {
	n.neLogDo.ReplaceDB(db)
	return n
}

type neLogDo struct{ gen.DO }

type INeLogDo interface {
	gen.SubQuery
	Debug() INeLogDo
	WithContext(ctx context.Context) INeLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INeLogDo
	WriteDB() INeLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INeLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INeLogDo
	Not(conds ...gen.Condition) INeLogDo
	Or(conds ...gen.Condition) INeLogDo
	Select(conds ...field.Expr) INeLogDo
	Where(conds ...gen.Condition) INeLogDo
	Order(conds ...field.Expr) INeLogDo
	Distinct(cols ...field.Expr) INeLogDo
	Omit(cols ...field.Expr) INeLogDo
	Join(table schema.Tabler, on ...field.Expr) INeLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INeLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INeLogDo
	Group(cols ...field.Expr) INeLogDo
	Having(conds ...gen.Condition) INeLogDo
	Limit(limit int) INeLogDo
	Offset(offset int) INeLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INeLogDo
	Unscoped() INeLogDo
	Create(values ...*model.NeLog) error
	CreateInBatches(values []*model.NeLog, batchSize int) error
	Save(values ...*model.NeLog) error
	First() (*model.NeLog, error)
	Take() (*model.NeLog, error)
	Last() (*model.NeLog, error)
	Find() ([]*model.NeLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NeLog, err error)
	FindInBatches(result *[]*model.NeLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NeLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INeLogDo
	Assign(attrs ...field.AssignExpr) INeLogDo
	Joins(fields ...field.RelationField) INeLogDo
	Preload(fields ...field.RelationField) INeLogDo
	FirstOrInit() (*model.NeLog, error)
	FirstOrCreate() (*model.NeLog, error)
	FindByPage(offset int, limit int) (result []*model.NeLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INeLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n neLogDo) Debug() INeLogDo {
	return n.withDO(n.DO.Debug())
}

func (n neLogDo) WithContext(ctx context.Context) INeLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n neLogDo) ReadDB() INeLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n neLogDo) WriteDB() INeLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n neLogDo) Session(config *gorm.Session) INeLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n neLogDo) Clauses(conds ...clause.Expression) INeLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n neLogDo) Returning(value interface{}, columns ...string) INeLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n neLogDo) Not(conds ...gen.Condition) INeLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n neLogDo) Or(conds ...gen.Condition) INeLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n neLogDo) Select(conds ...field.Expr) INeLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n neLogDo) Where(conds ...gen.Condition) INeLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n neLogDo) Order(conds ...field.Expr) INeLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n neLogDo) Distinct(cols ...field.Expr) INeLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n neLogDo) Omit(cols ...field.Expr) INeLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n neLogDo) Join(table schema.Tabler, on ...field.Expr) INeLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n neLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INeLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n neLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INeLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n neLogDo) Group(cols ...field.Expr) INeLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n neLogDo) Having(conds ...gen.Condition) INeLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n neLogDo) Limit(limit int) INeLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n neLogDo) Offset(offset int) INeLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n neLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INeLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n neLogDo) Unscoped() INeLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n neLogDo) Create(values ...*model.NeLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n neLogDo) CreateInBatches(values []*model.NeLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n neLogDo) Save(values ...*model.NeLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n neLogDo) First() (*model.NeLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeLog), nil
	}
}

func (n neLogDo) Take() (*model.NeLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeLog), nil
	}
}

func (n neLogDo) Last() (*model.NeLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeLog), nil
	}
}

func (n neLogDo) Find() ([]*model.NeLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NeLog), err
}

func (n neLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NeLog, err error) {
	buf := make([]*model.NeLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n neLogDo) FindInBatches(result *[]*model.NeLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n neLogDo) Attrs(attrs ...field.AssignExpr) INeLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n neLogDo) Assign(attrs ...field.AssignExpr) INeLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n neLogDo) Joins(fields ...field.RelationField) INeLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n neLogDo) Preload(fields ...field.RelationField) INeLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n neLogDo) FirstOrInit() (*model.NeLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeLog), nil
	}
}

func (n neLogDo) FirstOrCreate() (*model.NeLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeLog), nil
	}
}

func (n neLogDo) FindByPage(offset int, limit int) (result []*model.NeLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n neLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n neLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n neLogDo) Delete(models ...*model.NeLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *neLogDo) withDO(do gen.Dao) *neLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
