// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNePeProductOrderLog(db *gorm.DB, opts ...gen.DOOption) nePeProductOrderLog {
	_nePeProductOrderLog := nePeProductOrderLog{}

	_nePeProductOrderLog.nePeProductOrderLogDo.UseDB(db, opts...)
	_nePeProductOrderLog.nePeProductOrderLogDo.UseModel(&model.NePeProductOrderLog{})

	tableName := _nePeProductOrderLog.nePeProductOrderLogDo.TableName()
	_nePeProductOrderLog.ALL = field.NewAsterisk(tableName)
	_nePeProductOrderLog.ID = field.NewInt64(tableName, "id")
	_nePeProductOrderLog.NePeProductLogID = field.NewInt64(tableName, "ne_pe_product_log_id")
	_nePeProductOrderLog.AppOrderID = field.NewString(tableName, "app_order_id")
	_nePeProductOrderLog.AppOrderIDInt = field.NewInt64(tableName, "app_order_id_int")
	_nePeProductOrderLog.AppUID = field.NewString(tableName, "app_uid")
	_nePeProductOrderLog.AppUIDInt = field.NewInt64(tableName, "app_uid_int")
	_nePeProductOrderLog.Discount = field.NewString(tableName, "discount")
	_nePeProductOrderLog.OfficialChannel = field.NewInt32(tableName, "official_channel")
	_nePeProductOrderLog.Point = field.NewInt32(tableName, "point")
	_nePeProductOrderLog.PointType = field.NewString(tableName, "point_type")
	_nePeProductOrderLog.Price = field.NewInt32(tableName, "price")
	_nePeProductOrderLog.PriceType = field.NewString(tableName, "price_type")
	_nePeProductOrderLog.ProductName = field.NewString(tableName, "product_name")
	_nePeProductOrderLog.PurchaseLimit = field.NewInt32(tableName, "purchase_limit")
	_nePeProductOrderLog.RefundStatus = field.NewString(tableName, "refund_status")
	_nePeProductOrderLog.ShipTime = field.NewString(tableName, "ship_time")
	_nePeProductOrderLog.ShipTimeMs = field.NewInt64(tableName, "ship_time_ms")

	_nePeProductOrderLog.fillFieldMap()

	return _nePeProductOrderLog
}

type nePeProductOrderLog struct {
	nePeProductOrderLogDo nePeProductOrderLogDo

	ALL              field.Asterisk
	ID               field.Int64
	NePeProductLogID field.Int64
	AppOrderID       field.String
	AppOrderIDInt    field.Int64
	AppUID           field.String
	AppUIDInt        field.Int64
	Discount         field.String
	OfficialChannel  field.Int32
	Point            field.Int32
	PointType        field.String
	Price            field.Int32
	PriceType        field.String
	ProductName      field.String
	PurchaseLimit    field.Int32
	RefundStatus     field.String
	ShipTime         field.String
	ShipTimeMs       field.Int64

	fieldMap map[string]field.Expr
}

func (n nePeProductOrderLog) Table(newTableName string) *nePeProductOrderLog {
	n.nePeProductOrderLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nePeProductOrderLog) As(alias string) *nePeProductOrderLog {
	n.nePeProductOrderLogDo.DO = *(n.nePeProductOrderLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nePeProductOrderLog) updateTableName(table string) *nePeProductOrderLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NePeProductLogID = field.NewInt64(table, "ne_pe_product_log_id")
	n.AppOrderID = field.NewString(table, "app_order_id")
	n.AppOrderIDInt = field.NewInt64(table, "app_order_id_int")
	n.AppUID = field.NewString(table, "app_uid")
	n.AppUIDInt = field.NewInt64(table, "app_uid_int")
	n.Discount = field.NewString(table, "discount")
	n.OfficialChannel = field.NewInt32(table, "official_channel")
	n.Point = field.NewInt32(table, "point")
	n.PointType = field.NewString(table, "point_type")
	n.Price = field.NewInt32(table, "price")
	n.PriceType = field.NewString(table, "price_type")
	n.ProductName = field.NewString(table, "product_name")
	n.PurchaseLimit = field.NewInt32(table, "purchase_limit")
	n.RefundStatus = field.NewString(table, "refund_status")
	n.ShipTime = field.NewString(table, "ship_time")
	n.ShipTimeMs = field.NewInt64(table, "ship_time_ms")

	n.fillFieldMap()

	return n
}

func (n *nePeProductOrderLog) WithContext(ctx context.Context) INePeProductOrderLogDo {
	return n.nePeProductOrderLogDo.WithContext(ctx)
}

func (n nePeProductOrderLog) TableName() string { return n.nePeProductOrderLogDo.TableName() }

func (n nePeProductOrderLog) Alias() string { return n.nePeProductOrderLogDo.Alias() }

func (n nePeProductOrderLog) Columns(cols ...field.Expr) gen.Columns {
	return n.nePeProductOrderLogDo.Columns(cols...)
}

func (n *nePeProductOrderLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nePeProductOrderLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 17)
	n.fieldMap["id"] = n.ID
	n.fieldMap["ne_pe_product_log_id"] = n.NePeProductLogID
	n.fieldMap["app_order_id"] = n.AppOrderID
	n.fieldMap["app_order_id_int"] = n.AppOrderIDInt
	n.fieldMap["app_uid"] = n.AppUID
	n.fieldMap["app_uid_int"] = n.AppUIDInt
	n.fieldMap["discount"] = n.Discount
	n.fieldMap["official_channel"] = n.OfficialChannel
	n.fieldMap["point"] = n.Point
	n.fieldMap["point_type"] = n.PointType
	n.fieldMap["price"] = n.Price
	n.fieldMap["price_type"] = n.PriceType
	n.fieldMap["product_name"] = n.ProductName
	n.fieldMap["purchase_limit"] = n.PurchaseLimit
	n.fieldMap["refund_status"] = n.RefundStatus
	n.fieldMap["ship_time"] = n.ShipTime
	n.fieldMap["ship_time_ms"] = n.ShipTimeMs
}

func (n nePeProductOrderLog) clone(db *gorm.DB) nePeProductOrderLog {
	n.nePeProductOrderLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nePeProductOrderLog) replaceDB(db *gorm.DB) nePeProductOrderLog {
	n.nePeProductOrderLogDo.ReplaceDB(db)
	return n
}

type nePeProductOrderLogDo struct{ gen.DO }

type INePeProductOrderLogDo interface {
	gen.SubQuery
	Debug() INePeProductOrderLogDo
	WithContext(ctx context.Context) INePeProductOrderLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INePeProductOrderLogDo
	WriteDB() INePeProductOrderLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INePeProductOrderLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INePeProductOrderLogDo
	Not(conds ...gen.Condition) INePeProductOrderLogDo
	Or(conds ...gen.Condition) INePeProductOrderLogDo
	Select(conds ...field.Expr) INePeProductOrderLogDo
	Where(conds ...gen.Condition) INePeProductOrderLogDo
	Order(conds ...field.Expr) INePeProductOrderLogDo
	Distinct(cols ...field.Expr) INePeProductOrderLogDo
	Omit(cols ...field.Expr) INePeProductOrderLogDo
	Join(table schema.Tabler, on ...field.Expr) INePeProductOrderLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductOrderLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INePeProductOrderLogDo
	Group(cols ...field.Expr) INePeProductOrderLogDo
	Having(conds ...gen.Condition) INePeProductOrderLogDo
	Limit(limit int) INePeProductOrderLogDo
	Offset(offset int) INePeProductOrderLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductOrderLogDo
	Unscoped() INePeProductOrderLogDo
	Create(values ...*model.NePeProductOrderLog) error
	CreateInBatches(values []*model.NePeProductOrderLog, batchSize int) error
	Save(values ...*model.NePeProductOrderLog) error
	First() (*model.NePeProductOrderLog, error)
	Take() (*model.NePeProductOrderLog, error)
	Last() (*model.NePeProductOrderLog, error)
	Find() ([]*model.NePeProductOrderLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductOrderLog, err error)
	FindInBatches(result *[]*model.NePeProductOrderLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NePeProductOrderLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INePeProductOrderLogDo
	Assign(attrs ...field.AssignExpr) INePeProductOrderLogDo
	Joins(fields ...field.RelationField) INePeProductOrderLogDo
	Preload(fields ...field.RelationField) INePeProductOrderLogDo
	FirstOrInit() (*model.NePeProductOrderLog, error)
	FirstOrCreate() (*model.NePeProductOrderLog, error)
	FindByPage(offset int, limit int) (result []*model.NePeProductOrderLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INePeProductOrderLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nePeProductOrderLogDo) Debug() INePeProductOrderLogDo {
	return n.withDO(n.DO.Debug())
}

func (n nePeProductOrderLogDo) WithContext(ctx context.Context) INePeProductOrderLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nePeProductOrderLogDo) ReadDB() INePeProductOrderLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n nePeProductOrderLogDo) WriteDB() INePeProductOrderLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n nePeProductOrderLogDo) Session(config *gorm.Session) INePeProductOrderLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n nePeProductOrderLogDo) Clauses(conds ...clause.Expression) INePeProductOrderLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nePeProductOrderLogDo) Returning(value interface{}, columns ...string) INePeProductOrderLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nePeProductOrderLogDo) Not(conds ...gen.Condition) INePeProductOrderLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nePeProductOrderLogDo) Or(conds ...gen.Condition) INePeProductOrderLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nePeProductOrderLogDo) Select(conds ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nePeProductOrderLogDo) Where(conds ...gen.Condition) INePeProductOrderLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nePeProductOrderLogDo) Order(conds ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nePeProductOrderLogDo) Distinct(cols ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nePeProductOrderLogDo) Omit(cols ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nePeProductOrderLogDo) Join(table schema.Tabler, on ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nePeProductOrderLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nePeProductOrderLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nePeProductOrderLogDo) Group(cols ...field.Expr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nePeProductOrderLogDo) Having(conds ...gen.Condition) INePeProductOrderLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nePeProductOrderLogDo) Limit(limit int) INePeProductOrderLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nePeProductOrderLogDo) Offset(offset int) INePeProductOrderLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nePeProductOrderLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductOrderLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nePeProductOrderLogDo) Unscoped() INePeProductOrderLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nePeProductOrderLogDo) Create(values ...*model.NePeProductOrderLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nePeProductOrderLogDo) CreateInBatches(values []*model.NePeProductOrderLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nePeProductOrderLogDo) Save(values ...*model.NePeProductOrderLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nePeProductOrderLogDo) First() (*model.NePeProductOrderLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductOrderLog), nil
	}
}

func (n nePeProductOrderLogDo) Take() (*model.NePeProductOrderLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductOrderLog), nil
	}
}

func (n nePeProductOrderLogDo) Last() (*model.NePeProductOrderLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductOrderLog), nil
	}
}

func (n nePeProductOrderLogDo) Find() ([]*model.NePeProductOrderLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NePeProductOrderLog), err
}

func (n nePeProductOrderLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductOrderLog, err error) {
	buf := make([]*model.NePeProductOrderLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nePeProductOrderLogDo) FindInBatches(result *[]*model.NePeProductOrderLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nePeProductOrderLogDo) Attrs(attrs ...field.AssignExpr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nePeProductOrderLogDo) Assign(attrs ...field.AssignExpr) INePeProductOrderLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nePeProductOrderLogDo) Joins(fields ...field.RelationField) INePeProductOrderLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nePeProductOrderLogDo) Preload(fields ...field.RelationField) INePeProductOrderLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nePeProductOrderLogDo) FirstOrInit() (*model.NePeProductOrderLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductOrderLog), nil
	}
}

func (n nePeProductOrderLogDo) FirstOrCreate() (*model.NePeProductOrderLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductOrderLog), nil
	}
}

func (n nePeProductOrderLogDo) FindByPage(offset int, limit int) (result []*model.NePeProductOrderLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nePeProductOrderLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nePeProductOrderLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nePeProductOrderLogDo) Delete(models ...*model.NePeProductOrderLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nePeProductOrderLogDo) withDO(do gen.Dao) *nePeProductOrderLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
