// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNePeProductLog(db *gorm.DB, opts ...gen.DOOption) nePeProductLog {
	_nePeProductLog := nePeProductLog{}

	_nePeProductLog.nePeProductLogDo.UseDB(db, opts...)
	_nePeProductLog.nePeProductLogDo.UseModel(&model.NePeProductLog{})

	tableName := _nePeProductLog.nePeProductLogDo.TableName()
	_nePeProductLog.ALL = field.NewAsterisk(tableName)
	_nePeProductLog.ID = field.NewInt64(tableName, "id")
	_nePeProductLog.NeUserLogID = field.NewInt64(tableName, "ne_user_log_id")
	_nePeProductLog.ApplyReviewTime = field.NewString(tableName, "apply_review_time")
	_nePeProductLog.ApplyReviewTimeMs = field.NewInt64(tableName, "apply_review_time_ms")
	_nePeProductLog.CanManageServer = field.NewBool(tableName, "can_manage_server")
	_nePeProductLog.CanSilentOnline = field.NewBool(tableName, "can_silent_online")
	_nePeProductLog.CanSynchronizePc = field.NewBool(tableName, "can_synchronize_pc")
	_nePeProductLog.CanUpdatePc = field.NewBool(tableName, "can_update_pc")
	_nePeProductLog.CollectionID = field.NewInt32(tableName, "collection_id")
	_nePeProductLog.CreateTime = field.NewString(tableName, "create_time")
	_nePeProductLog.CreateTimeMs = field.NewInt64(tableName, "create_time_ms")
	_nePeProductLog.Discount = field.NewString(tableName, "discount")
	_nePeProductLog.ExemptPerfReviewNum = field.NewInt32(tableName, "exempt_perf_review_num")
	_nePeProductLog.InterceptFields = field.NewString(tableName, "intercept_fields")
	_nePeProductLog.IsEa = field.NewInt32(tableName, "is_ea")
	_nePeProductLog.IsOriginal = field.NewBool(tableName, "is_original")
	_nePeProductLog.IsSilentOnline = field.NewBool(tableName, "is_silent_online")
	_nePeProductLog.IsSuitablePc = field.NewBool(tableName, "is_suitable_pc")
	_nePeProductLog.IsSync = field.NewBool(tableName, "is_sync")
	_nePeProductLog.IsTestServer = field.NewBool(tableName, "is_test_server")
	_nePeProductLog.ItemID = field.NewString(tableName, "item_id")
	_nePeProductLog.ItemName = field.NewString(tableName, "item_name")
	_nePeProductLog.LobbyConfigOpLog = field.NewString(tableName, "lobby_config_op_log")
	_nePeProductLog.LobbySortKey = field.NewString(tableName, "lobby_sort_key")
	_nePeProductLog.OnlineTime = field.NewString(tableName, "online_time")
	_nePeProductLog.OnlineTimeMs = field.NewInt64(tableName, "online_time_ms")
	_nePeProductLog.OriWeakOffline = field.NewBool(tableName, "ori_weak_offline")
	_nePeProductLog.OriWeakOfflineReason = field.NewString(tableName, "ori_weak_offline_reason")
	_nePeProductLog.PeIsAddPlayPlan = field.NewBool(tableName, "pe_is_add_play_plan")
	_nePeProductLog.PerfData = field.NewString(tableName, "perf_data")
	_nePeProductLog.PerformanceServiceAvailable = field.NewInt32(tableName, "performance_service_available")
	_nePeProductLog.PerformanceServiceStatus = field.NewInt32(tableName, "performance_service_status")
	_nePeProductLog.PlayPlanExpireMonth = field.NewInt32(tableName, "play_plan_expire_month")
	_nePeProductLog.PriType = field.NewInt32(tableName, "pri_type")
	_nePeProductLog.Price = field.NewInt32(tableName, "price")
	_nePeProductLog.PriceRank = field.NewInt32(tableName, "price_rank")
	_nePeProductLog.PriceType = field.NewString(tableName, "price_type")
	_nePeProductLog.QueuePosition = field.NewInt32(tableName, "queue_position")
	_nePeProductLog.RatingLevel = field.NewInt32(tableName, "rating_level")
	_nePeProductLog.Remindable = field.NewBool(tableName, "remindable")
	_nePeProductLog.Res = field.NewString(tableName, "res")
	_nePeProductLog.Status = field.NewString(tableName, "status")
	_nePeProductLog.SyncItemInfo = field.NewString(tableName, "sync_item_info")
	_nePeProductLog.SyncPcFlag = field.NewBool(tableName, "sync_pc_flag")
	_nePeProductLog.UrgentStatus = field.NewInt32(tableName, "urgent_status")
	_nePeProductLog.WeakOffline = field.NewBool(tableName, "weak_offline")
	_nePeProductLog.WeakOfflineReason = field.NewString(tableName, "weak_offline_reason")
	_nePeProductLog.OrderPayload = field.NewString(tableName, "order_payload")
	_nePeProductLog.StatPayload = field.NewString(tableName, "stat_payload")

	_nePeProductLog.fillFieldMap()

	return _nePeProductLog
}

type nePeProductLog struct {
	nePeProductLogDo nePeProductLogDo

	ALL                         field.Asterisk
	ID                          field.Int64
	NeUserLogID                 field.Int64
	ApplyReviewTime             field.String
	ApplyReviewTimeMs           field.Int64
	CanManageServer             field.Bool
	CanSilentOnline             field.Bool
	CanSynchronizePc            field.Bool
	CanUpdatePc                 field.Bool
	CollectionID                field.Int32
	CreateTime                  field.String
	CreateTimeMs                field.Int64
	Discount                    field.String
	ExemptPerfReviewNum         field.Int32
	InterceptFields             field.String
	IsEa                        field.Int32
	IsOriginal                  field.Bool
	IsSilentOnline              field.Bool
	IsSuitablePc                field.Bool
	IsSync                      field.Bool
	IsTestServer                field.Bool
	ItemID                      field.String
	ItemName                    field.String
	LobbyConfigOpLog            field.String
	LobbySortKey                field.String
	OnlineTime                  field.String
	OnlineTimeMs                field.Int64
	OriWeakOffline              field.Bool
	OriWeakOfflineReason        field.String
	PeIsAddPlayPlan             field.Bool
	PerfData                    field.String
	PerformanceServiceAvailable field.Int32
	PerformanceServiceStatus    field.Int32
	PlayPlanExpireMonth         field.Int32
	PriType                     field.Int32
	Price                       field.Int32
	PriceRank                   field.Int32
	PriceType                   field.String
	QueuePosition               field.Int32
	RatingLevel                 field.Int32
	Remindable                  field.Bool
	Res                         field.String
	Status                      field.String
	SyncItemInfo                field.String
	SyncPcFlag                  field.Bool
	UrgentStatus                field.Int32
	WeakOffline                 field.Bool
	WeakOfflineReason           field.String
	OrderPayload                field.String
	StatPayload                 field.String

	fieldMap map[string]field.Expr
}

func (n nePeProductLog) Table(newTableName string) *nePeProductLog {
	n.nePeProductLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nePeProductLog) As(alias string) *nePeProductLog {
	n.nePeProductLogDo.DO = *(n.nePeProductLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nePeProductLog) updateTableName(table string) *nePeProductLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NeUserLogID = field.NewInt64(table, "ne_user_log_id")
	n.ApplyReviewTime = field.NewString(table, "apply_review_time")
	n.ApplyReviewTimeMs = field.NewInt64(table, "apply_review_time_ms")
	n.CanManageServer = field.NewBool(table, "can_manage_server")
	n.CanSilentOnline = field.NewBool(table, "can_silent_online")
	n.CanSynchronizePc = field.NewBool(table, "can_synchronize_pc")
	n.CanUpdatePc = field.NewBool(table, "can_update_pc")
	n.CollectionID = field.NewInt32(table, "collection_id")
	n.CreateTime = field.NewString(table, "create_time")
	n.CreateTimeMs = field.NewInt64(table, "create_time_ms")
	n.Discount = field.NewString(table, "discount")
	n.ExemptPerfReviewNum = field.NewInt32(table, "exempt_perf_review_num")
	n.InterceptFields = field.NewString(table, "intercept_fields")
	n.IsEa = field.NewInt32(table, "is_ea")
	n.IsOriginal = field.NewBool(table, "is_original")
	n.IsSilentOnline = field.NewBool(table, "is_silent_online")
	n.IsSuitablePc = field.NewBool(table, "is_suitable_pc")
	n.IsSync = field.NewBool(table, "is_sync")
	n.IsTestServer = field.NewBool(table, "is_test_server")
	n.ItemID = field.NewString(table, "item_id")
	n.ItemName = field.NewString(table, "item_name")
	n.LobbyConfigOpLog = field.NewString(table, "lobby_config_op_log")
	n.LobbySortKey = field.NewString(table, "lobby_sort_key")
	n.OnlineTime = field.NewString(table, "online_time")
	n.OnlineTimeMs = field.NewInt64(table, "online_time_ms")
	n.OriWeakOffline = field.NewBool(table, "ori_weak_offline")
	n.OriWeakOfflineReason = field.NewString(table, "ori_weak_offline_reason")
	n.PeIsAddPlayPlan = field.NewBool(table, "pe_is_add_play_plan")
	n.PerfData = field.NewString(table, "perf_data")
	n.PerformanceServiceAvailable = field.NewInt32(table, "performance_service_available")
	n.PerformanceServiceStatus = field.NewInt32(table, "performance_service_status")
	n.PlayPlanExpireMonth = field.NewInt32(table, "play_plan_expire_month")
	n.PriType = field.NewInt32(table, "pri_type")
	n.Price = field.NewInt32(table, "price")
	n.PriceRank = field.NewInt32(table, "price_rank")
	n.PriceType = field.NewString(table, "price_type")
	n.QueuePosition = field.NewInt32(table, "queue_position")
	n.RatingLevel = field.NewInt32(table, "rating_level")
	n.Remindable = field.NewBool(table, "remindable")
	n.Res = field.NewString(table, "res")
	n.Status = field.NewString(table, "status")
	n.SyncItemInfo = field.NewString(table, "sync_item_info")
	n.SyncPcFlag = field.NewBool(table, "sync_pc_flag")
	n.UrgentStatus = field.NewInt32(table, "urgent_status")
	n.WeakOffline = field.NewBool(table, "weak_offline")
	n.WeakOfflineReason = field.NewString(table, "weak_offline_reason")
	n.OrderPayload = field.NewString(table, "order_payload")
	n.StatPayload = field.NewString(table, "stat_payload")

	n.fillFieldMap()

	return n
}

func (n *nePeProductLog) WithContext(ctx context.Context) INePeProductLogDo {
	return n.nePeProductLogDo.WithContext(ctx)
}

func (n nePeProductLog) TableName() string { return n.nePeProductLogDo.TableName() }

func (n nePeProductLog) Alias() string { return n.nePeProductLogDo.Alias() }

func (n nePeProductLog) Columns(cols ...field.Expr) gen.Columns {
	return n.nePeProductLogDo.Columns(cols...)
}

func (n *nePeProductLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nePeProductLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 49)
	n.fieldMap["id"] = n.ID
	n.fieldMap["ne_user_log_id"] = n.NeUserLogID
	n.fieldMap["apply_review_time"] = n.ApplyReviewTime
	n.fieldMap["apply_review_time_ms"] = n.ApplyReviewTimeMs
	n.fieldMap["can_manage_server"] = n.CanManageServer
	n.fieldMap["can_silent_online"] = n.CanSilentOnline
	n.fieldMap["can_synchronize_pc"] = n.CanSynchronizePc
	n.fieldMap["can_update_pc"] = n.CanUpdatePc
	n.fieldMap["collection_id"] = n.CollectionID
	n.fieldMap["create_time"] = n.CreateTime
	n.fieldMap["create_time_ms"] = n.CreateTimeMs
	n.fieldMap["discount"] = n.Discount
	n.fieldMap["exempt_perf_review_num"] = n.ExemptPerfReviewNum
	n.fieldMap["intercept_fields"] = n.InterceptFields
	n.fieldMap["is_ea"] = n.IsEa
	n.fieldMap["is_original"] = n.IsOriginal
	n.fieldMap["is_silent_online"] = n.IsSilentOnline
	n.fieldMap["is_suitable_pc"] = n.IsSuitablePc
	n.fieldMap["is_sync"] = n.IsSync
	n.fieldMap["is_test_server"] = n.IsTestServer
	n.fieldMap["item_id"] = n.ItemID
	n.fieldMap["item_name"] = n.ItemName
	n.fieldMap["lobby_config_op_log"] = n.LobbyConfigOpLog
	n.fieldMap["lobby_sort_key"] = n.LobbySortKey
	n.fieldMap["online_time"] = n.OnlineTime
	n.fieldMap["online_time_ms"] = n.OnlineTimeMs
	n.fieldMap["ori_weak_offline"] = n.OriWeakOffline
	n.fieldMap["ori_weak_offline_reason"] = n.OriWeakOfflineReason
	n.fieldMap["pe_is_add_play_plan"] = n.PeIsAddPlayPlan
	n.fieldMap["perf_data"] = n.PerfData
	n.fieldMap["performance_service_available"] = n.PerformanceServiceAvailable
	n.fieldMap["performance_service_status"] = n.PerformanceServiceStatus
	n.fieldMap["play_plan_expire_month"] = n.PlayPlanExpireMonth
	n.fieldMap["pri_type"] = n.PriType
	n.fieldMap["price"] = n.Price
	n.fieldMap["price_rank"] = n.PriceRank
	n.fieldMap["price_type"] = n.PriceType
	n.fieldMap["queue_position"] = n.QueuePosition
	n.fieldMap["rating_level"] = n.RatingLevel
	n.fieldMap["remindable"] = n.Remindable
	n.fieldMap["res"] = n.Res
	n.fieldMap["status"] = n.Status
	n.fieldMap["sync_item_info"] = n.SyncItemInfo
	n.fieldMap["sync_pc_flag"] = n.SyncPcFlag
	n.fieldMap["urgent_status"] = n.UrgentStatus
	n.fieldMap["weak_offline"] = n.WeakOffline
	n.fieldMap["weak_offline_reason"] = n.WeakOfflineReason
	n.fieldMap["order_payload"] = n.OrderPayload
	n.fieldMap["stat_payload"] = n.StatPayload
}

func (n nePeProductLog) clone(db *gorm.DB) nePeProductLog {
	n.nePeProductLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nePeProductLog) replaceDB(db *gorm.DB) nePeProductLog {
	n.nePeProductLogDo.ReplaceDB(db)
	return n
}

type nePeProductLogDo struct{ gen.DO }

type INePeProductLogDo interface {
	gen.SubQuery
	Debug() INePeProductLogDo
	WithContext(ctx context.Context) INePeProductLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INePeProductLogDo
	WriteDB() INePeProductLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INePeProductLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INePeProductLogDo
	Not(conds ...gen.Condition) INePeProductLogDo
	Or(conds ...gen.Condition) INePeProductLogDo
	Select(conds ...field.Expr) INePeProductLogDo
	Where(conds ...gen.Condition) INePeProductLogDo
	Order(conds ...field.Expr) INePeProductLogDo
	Distinct(cols ...field.Expr) INePeProductLogDo
	Omit(cols ...field.Expr) INePeProductLogDo
	Join(table schema.Tabler, on ...field.Expr) INePeProductLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INePeProductLogDo
	Group(cols ...field.Expr) INePeProductLogDo
	Having(conds ...gen.Condition) INePeProductLogDo
	Limit(limit int) INePeProductLogDo
	Offset(offset int) INePeProductLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductLogDo
	Unscoped() INePeProductLogDo
	Create(values ...*model.NePeProductLog) error
	CreateInBatches(values []*model.NePeProductLog, batchSize int) error
	Save(values ...*model.NePeProductLog) error
	First() (*model.NePeProductLog, error)
	Take() (*model.NePeProductLog, error)
	Last() (*model.NePeProductLog, error)
	Find() ([]*model.NePeProductLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductLog, err error)
	FindInBatches(result *[]*model.NePeProductLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NePeProductLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INePeProductLogDo
	Assign(attrs ...field.AssignExpr) INePeProductLogDo
	Joins(fields ...field.RelationField) INePeProductLogDo
	Preload(fields ...field.RelationField) INePeProductLogDo
	FirstOrInit() (*model.NePeProductLog, error)
	FirstOrCreate() (*model.NePeProductLog, error)
	FindByPage(offset int, limit int) (result []*model.NePeProductLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INePeProductLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nePeProductLogDo) Debug() INePeProductLogDo {
	return n.withDO(n.DO.Debug())
}

func (n nePeProductLogDo) WithContext(ctx context.Context) INePeProductLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nePeProductLogDo) ReadDB() INePeProductLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n nePeProductLogDo) WriteDB() INePeProductLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n nePeProductLogDo) Session(config *gorm.Session) INePeProductLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n nePeProductLogDo) Clauses(conds ...clause.Expression) INePeProductLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nePeProductLogDo) Returning(value interface{}, columns ...string) INePeProductLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nePeProductLogDo) Not(conds ...gen.Condition) INePeProductLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nePeProductLogDo) Or(conds ...gen.Condition) INePeProductLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nePeProductLogDo) Select(conds ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nePeProductLogDo) Where(conds ...gen.Condition) INePeProductLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nePeProductLogDo) Order(conds ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nePeProductLogDo) Distinct(cols ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nePeProductLogDo) Omit(cols ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nePeProductLogDo) Join(table schema.Tabler, on ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nePeProductLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nePeProductLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nePeProductLogDo) Group(cols ...field.Expr) INePeProductLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nePeProductLogDo) Having(conds ...gen.Condition) INePeProductLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nePeProductLogDo) Limit(limit int) INePeProductLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nePeProductLogDo) Offset(offset int) INePeProductLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nePeProductLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nePeProductLogDo) Unscoped() INePeProductLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nePeProductLogDo) Create(values ...*model.NePeProductLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nePeProductLogDo) CreateInBatches(values []*model.NePeProductLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nePeProductLogDo) Save(values ...*model.NePeProductLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nePeProductLogDo) First() (*model.NePeProductLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductLog), nil
	}
}

func (n nePeProductLogDo) Take() (*model.NePeProductLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductLog), nil
	}
}

func (n nePeProductLogDo) Last() (*model.NePeProductLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductLog), nil
	}
}

func (n nePeProductLogDo) Find() ([]*model.NePeProductLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NePeProductLog), err
}

func (n nePeProductLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductLog, err error) {
	buf := make([]*model.NePeProductLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nePeProductLogDo) FindInBatches(result *[]*model.NePeProductLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nePeProductLogDo) Attrs(attrs ...field.AssignExpr) INePeProductLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nePeProductLogDo) Assign(attrs ...field.AssignExpr) INePeProductLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nePeProductLogDo) Joins(fields ...field.RelationField) INePeProductLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nePeProductLogDo) Preload(fields ...field.RelationField) INePeProductLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nePeProductLogDo) FirstOrInit() (*model.NePeProductLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductLog), nil
	}
}

func (n nePeProductLogDo) FirstOrCreate() (*model.NePeProductLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductLog), nil
	}
}

func (n nePeProductLogDo) FindByPage(offset int, limit int) (result []*model.NePeProductLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nePeProductLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nePeProductLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nePeProductLogDo) Delete(models ...*model.NePeProductLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nePeProductLogDo) withDO(do gen.Dao) *nePeProductLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
