// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNePeProductStatLog(db *gorm.DB, opts ...gen.DOOption) nePeProductStatLog {
	_nePeProductStatLog := nePeProductStatLog{}

	_nePeProductStatLog.nePeProductStatLogDo.UseDB(db, opts...)
	_nePeProductStatLog.nePeProductStatLogDo.UseModel(&model.NePeProductStatLog{})

	tableName := _nePeProductStatLog.nePeProductStatLogDo.TableName()
	_nePeProductStatLog.ALL = field.NewAsterisk(tableName)
	_nePeProductStatLog.ID = field.NewInt64(tableName, "id")
	_nePeProductStatLog.NePeProductLogID = field.NewInt64(tableName, "ne_pe_product_log_id")
	_nePeProductStatLog.Dau = field.NewInt32(tableName, "dau")
	_nePeProductStatLog.AvgFirstTypeBuy = field.NewFloat64(tableName, "avg_first_type_buy")
	_nePeProductStatLog.AvgFirstTypeDiamond = field.NewFloat64(tableName, "avg_first_type_diamond")
	_nePeProductStatLog.AvgFirstTypeFocus = field.NewFloat64(tableName, "avg_first_type_focus")
	_nePeProductStatLog.AvgFirstTypeRolePlay = field.NewFloat64(tableName, "avg_first_type_role_play")
	_nePeProductStatLog.AvgPlaytime = field.NewFloat64(tableName, "avg_playtime")
	_nePeProductStatLog.AvgTotalFirstTypeBuy = field.NewFloat64(tableName, "avg_total_first_type_buy")
	_nePeProductStatLog.CntBuy = field.NewInt32(tableName, "cnt_buy")
	_nePeProductStatLog.DateID = field.NewString(tableName, "date_id")
	_nePeProductStatLog.DateMs = field.NewInt64(tableName, "date_ms")
	_nePeProductStatLog.Diamond = field.NewInt32(tableName, "diamond")
	_nePeProductStatLog.DownloadNum = field.NewInt32(tableName, "download_num")
	_nePeProductStatLog.FirstTypeAvgRoleTime = field.NewFloat64(tableName, "first_type_avg_role_time")
	_nePeProductStatLog.FocusCnt = field.NewInt32(tableName, "focus_cnt")
	_nePeProductStatLog.Iid = field.NewString(tableName, "iid")
	_nePeProductStatLog.IidInt = field.NewInt64(tableName, "iid_int")
	_nePeProductStatLog.PassAvgRoleTimeRatio = field.NewFloat64(tableName, "pass_avg_role_time_ratio")
	_nePeProductStatLog.PassBuyCntRatio = field.NewFloat64(tableName, "pass_buy_cnt_ratio")
	_nePeProductStatLog.PassCntRolePlayRatio = field.NewFloat64(tableName, "pass_cnt_role_play_ratio")
	_nePeProductStatLog.PassFocusCntRatio = field.NewFloat64(tableName, "pass_focus_cnt_ratio")
	_nePeProductStatLog.PassPayDiamondRatio = field.NewFloat64(tableName, "pass_pay_diamond_ratio")
	_nePeProductStatLog.Platform = field.NewString(tableName, "platform")
	_nePeProductStatLog.Points = field.NewInt32(tableName, "points")
	_nePeProductStatLog.RefundRate = field.NewFloat64(tableName, "refund_rate")
	_nePeProductStatLog.ResName = field.NewString(tableName, "res_name")
	_nePeProductStatLog.StarAdjusted = field.NewFloat64(tableName, "star_adjusted")
	_nePeProductStatLog.UploadTime = field.NewString(tableName, "upload_time")
	_nePeProductStatLog.UploadTimeMs = field.NewInt64(tableName, "upload_time_ms")

	_nePeProductStatLog.fillFieldMap()

	return _nePeProductStatLog
}

type nePeProductStatLog struct {
	nePeProductStatLogDo nePeProductStatLogDo

	ALL                  field.Asterisk
	ID                   field.Int64
	NePeProductLogID     field.Int64
	Dau                  field.Int32
	AvgFirstTypeBuy      field.Float64
	AvgFirstTypeDiamond  field.Float64
	AvgFirstTypeFocus    field.Float64
	AvgFirstTypeRolePlay field.Float64
	AvgPlaytime          field.Float64
	AvgTotalFirstTypeBuy field.Float64
	CntBuy               field.Int32
	DateID               field.String
	DateMs               field.Int64
	Diamond              field.Int32
	DownloadNum          field.Int32
	FirstTypeAvgRoleTime field.Float64
	FocusCnt             field.Int32
	Iid                  field.String
	IidInt               field.Int64
	PassAvgRoleTimeRatio field.Float64
	PassBuyCntRatio      field.Float64
	PassCntRolePlayRatio field.Float64
	PassFocusCntRatio    field.Float64
	PassPayDiamondRatio  field.Float64
	Platform             field.String
	Points               field.Int32
	RefundRate           field.Float64
	ResName              field.String
	StarAdjusted         field.Float64
	UploadTime           field.String
	UploadTimeMs         field.Int64

	fieldMap map[string]field.Expr
}

func (n nePeProductStatLog) Table(newTableName string) *nePeProductStatLog {
	n.nePeProductStatLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nePeProductStatLog) As(alias string) *nePeProductStatLog {
	n.nePeProductStatLogDo.DO = *(n.nePeProductStatLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nePeProductStatLog) updateTableName(table string) *nePeProductStatLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NePeProductLogID = field.NewInt64(table, "ne_pe_product_log_id")
	n.Dau = field.NewInt32(table, "dau")
	n.AvgFirstTypeBuy = field.NewFloat64(table, "avg_first_type_buy")
	n.AvgFirstTypeDiamond = field.NewFloat64(table, "avg_first_type_diamond")
	n.AvgFirstTypeFocus = field.NewFloat64(table, "avg_first_type_focus")
	n.AvgFirstTypeRolePlay = field.NewFloat64(table, "avg_first_type_role_play")
	n.AvgPlaytime = field.NewFloat64(table, "avg_playtime")
	n.AvgTotalFirstTypeBuy = field.NewFloat64(table, "avg_total_first_type_buy")
	n.CntBuy = field.NewInt32(table, "cnt_buy")
	n.DateID = field.NewString(table, "date_id")
	n.DateMs = field.NewInt64(table, "date_ms")
	n.Diamond = field.NewInt32(table, "diamond")
	n.DownloadNum = field.NewInt32(table, "download_num")
	n.FirstTypeAvgRoleTime = field.NewFloat64(table, "first_type_avg_role_time")
	n.FocusCnt = field.NewInt32(table, "focus_cnt")
	n.Iid = field.NewString(table, "iid")
	n.IidInt = field.NewInt64(table, "iid_int")
	n.PassAvgRoleTimeRatio = field.NewFloat64(table, "pass_avg_role_time_ratio")
	n.PassBuyCntRatio = field.NewFloat64(table, "pass_buy_cnt_ratio")
	n.PassCntRolePlayRatio = field.NewFloat64(table, "pass_cnt_role_play_ratio")
	n.PassFocusCntRatio = field.NewFloat64(table, "pass_focus_cnt_ratio")
	n.PassPayDiamondRatio = field.NewFloat64(table, "pass_pay_diamond_ratio")
	n.Platform = field.NewString(table, "platform")
	n.Points = field.NewInt32(table, "points")
	n.RefundRate = field.NewFloat64(table, "refund_rate")
	n.ResName = field.NewString(table, "res_name")
	n.StarAdjusted = field.NewFloat64(table, "star_adjusted")
	n.UploadTime = field.NewString(table, "upload_time")
	n.UploadTimeMs = field.NewInt64(table, "upload_time_ms")

	n.fillFieldMap()

	return n
}

func (n *nePeProductStatLog) WithContext(ctx context.Context) INePeProductStatLogDo {
	return n.nePeProductStatLogDo.WithContext(ctx)
}

func (n nePeProductStatLog) TableName() string { return n.nePeProductStatLogDo.TableName() }

func (n nePeProductStatLog) Alias() string { return n.nePeProductStatLogDo.Alias() }

func (n nePeProductStatLog) Columns(cols ...field.Expr) gen.Columns {
	return n.nePeProductStatLogDo.Columns(cols...)
}

func (n *nePeProductStatLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nePeProductStatLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 30)
	n.fieldMap["id"] = n.ID
	n.fieldMap["ne_pe_product_log_id"] = n.NePeProductLogID
	n.fieldMap["dau"] = n.Dau
	n.fieldMap["avg_first_type_buy"] = n.AvgFirstTypeBuy
	n.fieldMap["avg_first_type_diamond"] = n.AvgFirstTypeDiamond
	n.fieldMap["avg_first_type_focus"] = n.AvgFirstTypeFocus
	n.fieldMap["avg_first_type_role_play"] = n.AvgFirstTypeRolePlay
	n.fieldMap["avg_playtime"] = n.AvgPlaytime
	n.fieldMap["avg_total_first_type_buy"] = n.AvgTotalFirstTypeBuy
	n.fieldMap["cnt_buy"] = n.CntBuy
	n.fieldMap["date_id"] = n.DateID
	n.fieldMap["date_ms"] = n.DateMs
	n.fieldMap["diamond"] = n.Diamond
	n.fieldMap["download_num"] = n.DownloadNum
	n.fieldMap["first_type_avg_role_time"] = n.FirstTypeAvgRoleTime
	n.fieldMap["focus_cnt"] = n.FocusCnt
	n.fieldMap["iid"] = n.Iid
	n.fieldMap["iid_int"] = n.IidInt
	n.fieldMap["pass_avg_role_time_ratio"] = n.PassAvgRoleTimeRatio
	n.fieldMap["pass_buy_cnt_ratio"] = n.PassBuyCntRatio
	n.fieldMap["pass_cnt_role_play_ratio"] = n.PassCntRolePlayRatio
	n.fieldMap["pass_focus_cnt_ratio"] = n.PassFocusCntRatio
	n.fieldMap["pass_pay_diamond_ratio"] = n.PassPayDiamondRatio
	n.fieldMap["platform"] = n.Platform
	n.fieldMap["points"] = n.Points
	n.fieldMap["refund_rate"] = n.RefundRate
	n.fieldMap["res_name"] = n.ResName
	n.fieldMap["star_adjusted"] = n.StarAdjusted
	n.fieldMap["upload_time"] = n.UploadTime
	n.fieldMap["upload_time_ms"] = n.UploadTimeMs
}

func (n nePeProductStatLog) clone(db *gorm.DB) nePeProductStatLog {
	n.nePeProductStatLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nePeProductStatLog) replaceDB(db *gorm.DB) nePeProductStatLog {
	n.nePeProductStatLogDo.ReplaceDB(db)
	return n
}

type nePeProductStatLogDo struct{ gen.DO }

type INePeProductStatLogDo interface {
	gen.SubQuery
	Debug() INePeProductStatLogDo
	WithContext(ctx context.Context) INePeProductStatLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INePeProductStatLogDo
	WriteDB() INePeProductStatLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INePeProductStatLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INePeProductStatLogDo
	Not(conds ...gen.Condition) INePeProductStatLogDo
	Or(conds ...gen.Condition) INePeProductStatLogDo
	Select(conds ...field.Expr) INePeProductStatLogDo
	Where(conds ...gen.Condition) INePeProductStatLogDo
	Order(conds ...field.Expr) INePeProductStatLogDo
	Distinct(cols ...field.Expr) INePeProductStatLogDo
	Omit(cols ...field.Expr) INePeProductStatLogDo
	Join(table schema.Tabler, on ...field.Expr) INePeProductStatLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductStatLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INePeProductStatLogDo
	Group(cols ...field.Expr) INePeProductStatLogDo
	Having(conds ...gen.Condition) INePeProductStatLogDo
	Limit(limit int) INePeProductStatLogDo
	Offset(offset int) INePeProductStatLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductStatLogDo
	Unscoped() INePeProductStatLogDo
	Create(values ...*model.NePeProductStatLog) error
	CreateInBatches(values []*model.NePeProductStatLog, batchSize int) error
	Save(values ...*model.NePeProductStatLog) error
	First() (*model.NePeProductStatLog, error)
	Take() (*model.NePeProductStatLog, error)
	Last() (*model.NePeProductStatLog, error)
	Find() ([]*model.NePeProductStatLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductStatLog, err error)
	FindInBatches(result *[]*model.NePeProductStatLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NePeProductStatLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INePeProductStatLogDo
	Assign(attrs ...field.AssignExpr) INePeProductStatLogDo
	Joins(fields ...field.RelationField) INePeProductStatLogDo
	Preload(fields ...field.RelationField) INePeProductStatLogDo
	FirstOrInit() (*model.NePeProductStatLog, error)
	FirstOrCreate() (*model.NePeProductStatLog, error)
	FindByPage(offset int, limit int) (result []*model.NePeProductStatLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INePeProductStatLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nePeProductStatLogDo) Debug() INePeProductStatLogDo {
	return n.withDO(n.DO.Debug())
}

func (n nePeProductStatLogDo) WithContext(ctx context.Context) INePeProductStatLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nePeProductStatLogDo) ReadDB() INePeProductStatLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n nePeProductStatLogDo) WriteDB() INePeProductStatLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n nePeProductStatLogDo) Session(config *gorm.Session) INePeProductStatLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n nePeProductStatLogDo) Clauses(conds ...clause.Expression) INePeProductStatLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nePeProductStatLogDo) Returning(value interface{}, columns ...string) INePeProductStatLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nePeProductStatLogDo) Not(conds ...gen.Condition) INePeProductStatLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nePeProductStatLogDo) Or(conds ...gen.Condition) INePeProductStatLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nePeProductStatLogDo) Select(conds ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nePeProductStatLogDo) Where(conds ...gen.Condition) INePeProductStatLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nePeProductStatLogDo) Order(conds ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nePeProductStatLogDo) Distinct(cols ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nePeProductStatLogDo) Omit(cols ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nePeProductStatLogDo) Join(table schema.Tabler, on ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nePeProductStatLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nePeProductStatLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nePeProductStatLogDo) Group(cols ...field.Expr) INePeProductStatLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nePeProductStatLogDo) Having(conds ...gen.Condition) INePeProductStatLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nePeProductStatLogDo) Limit(limit int) INePeProductStatLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nePeProductStatLogDo) Offset(offset int) INePeProductStatLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nePeProductStatLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductStatLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nePeProductStatLogDo) Unscoped() INePeProductStatLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nePeProductStatLogDo) Create(values ...*model.NePeProductStatLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nePeProductStatLogDo) CreateInBatches(values []*model.NePeProductStatLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nePeProductStatLogDo) Save(values ...*model.NePeProductStatLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nePeProductStatLogDo) First() (*model.NePeProductStatLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductStatLog), nil
	}
}

func (n nePeProductStatLogDo) Take() (*model.NePeProductStatLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductStatLog), nil
	}
}

func (n nePeProductStatLogDo) Last() (*model.NePeProductStatLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductStatLog), nil
	}
}

func (n nePeProductStatLogDo) Find() ([]*model.NePeProductStatLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NePeProductStatLog), err
}

func (n nePeProductStatLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductStatLog, err error) {
	buf := make([]*model.NePeProductStatLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nePeProductStatLogDo) FindInBatches(result *[]*model.NePeProductStatLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nePeProductStatLogDo) Attrs(attrs ...field.AssignExpr) INePeProductStatLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nePeProductStatLogDo) Assign(attrs ...field.AssignExpr) INePeProductStatLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nePeProductStatLogDo) Joins(fields ...field.RelationField) INePeProductStatLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nePeProductStatLogDo) Preload(fields ...field.RelationField) INePeProductStatLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nePeProductStatLogDo) FirstOrInit() (*model.NePeProductStatLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductStatLog), nil
	}
}

func (n nePeProductStatLogDo) FirstOrCreate() (*model.NePeProductStatLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductStatLog), nil
	}
}

func (n nePeProductStatLogDo) FindByPage(offset int, limit int) (result []*model.NePeProductStatLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nePeProductStatLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nePeProductStatLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nePeProductStatLogDo) Delete(models ...*model.NePeProductStatLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nePeProductStatLogDo) withDO(do gen.Dao) *nePeProductStatLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
