// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNePeProductCommentLog(db *gorm.DB, opts ...gen.DOOption) nePeProductCommentLog {
	_nePeProductCommentLog := nePeProductCommentLog{}

	_nePeProductCommentLog.nePeProductCommentLogDo.UseDB(db, opts...)
	_nePeProductCommentLog.nePeProductCommentLogDo.UseModel(&model.NePeProductCommentLog{})

	tableName := _nePeProductCommentLog.nePeProductCommentLogDo.TableName()
	_nePeProductCommentLog.ALL = field.NewAsterisk(tableName)
	_nePeProductCommentLog.ID = field.NewInt64(tableName, "id")
	_nePeProductCommentLog.CommentID = field.NewString(tableName, "comment_id")
	_nePeProductCommentLog.CommentState = field.NewString(tableName, "comment_state")
	_nePeProductCommentLog.CommentTag = field.NewString(tableName, "comment_tag")
	_nePeProductCommentLog.CommentedNum = field.NewString(tableName, "commented_num")
	_nePeProductCommentLog.CommentedNumInt = field.NewInt64(tableName, "commented_num_int")
	_nePeProductCommentLog.GoodNum = field.NewString(tableName, "good_num")
	_nePeProductCommentLog.GoodNumInt = field.NewInt64(tableName, "good_num_int")
	_nePeProductCommentLog.Iid = field.NewString(tableName, "iid")
	_nePeProductCommentLog.IidInt = field.NewInt64(tableName, "iid_int")
	_nePeProductCommentLog.MasterID = field.NewString(tableName, "master_id")
	_nePeProductCommentLog.MasterIDInt = field.NewInt64(tableName, "master_id_int")
	_nePeProductCommentLog.Nickname = field.NewString(tableName, "nickname")
	_nePeProductCommentLog.PublishTime = field.NewString(tableName, "publish_time")
	_nePeProductCommentLog.PublishTimeMs = field.NewInt64(tableName, "publish_time_ms")
	_nePeProductCommentLog.ReplyID = field.NewString(tableName, "reply_id")
	_nePeProductCommentLog.ReplyIDInt = field.NewInt64(tableName, "reply_id_int")
	_nePeProductCommentLog.ResName = field.NewString(tableName, "res_name")
	_nePeProductCommentLog.Stars = field.NewString(tableName, "stars")
	_nePeProductCommentLog.StarsInt = field.NewInt64(tableName, "stars_int")
	_nePeProductCommentLog.UID = field.NewString(tableName, "uid")
	_nePeProductCommentLog.UIDInt = field.NewInt64(tableName, "uid_int")
	_nePeProductCommentLog.UserComment = field.NewString(tableName, "user_comment")

	_nePeProductCommentLog.fillFieldMap()

	return _nePeProductCommentLog
}

type nePeProductCommentLog struct {
	nePeProductCommentLogDo nePeProductCommentLogDo

	ALL             field.Asterisk
	ID              field.Int64
	CommentID       field.String
	CommentState    field.String
	CommentTag      field.String
	CommentedNum    field.String
	CommentedNumInt field.Int64
	GoodNum         field.String
	GoodNumInt      field.Int64
	Iid             field.String
	IidInt          field.Int64
	MasterID        field.String
	MasterIDInt     field.Int64
	Nickname        field.String
	PublishTime     field.String
	PublishTimeMs   field.Int64
	ReplyID         field.String
	ReplyIDInt      field.Int64
	ResName         field.String
	Stars           field.String
	StarsInt        field.Int64
	UID             field.String
	UIDInt          field.Int64
	UserComment     field.String

	fieldMap map[string]field.Expr
}

func (n nePeProductCommentLog) Table(newTableName string) *nePeProductCommentLog {
	n.nePeProductCommentLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nePeProductCommentLog) As(alias string) *nePeProductCommentLog {
	n.nePeProductCommentLogDo.DO = *(n.nePeProductCommentLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nePeProductCommentLog) updateTableName(table string) *nePeProductCommentLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.CommentID = field.NewString(table, "comment_id")
	n.CommentState = field.NewString(table, "comment_state")
	n.CommentTag = field.NewString(table, "comment_tag")
	n.CommentedNum = field.NewString(table, "commented_num")
	n.CommentedNumInt = field.NewInt64(table, "commented_num_int")
	n.GoodNum = field.NewString(table, "good_num")
	n.GoodNumInt = field.NewInt64(table, "good_num_int")
	n.Iid = field.NewString(table, "iid")
	n.IidInt = field.NewInt64(table, "iid_int")
	n.MasterID = field.NewString(table, "master_id")
	n.MasterIDInt = field.NewInt64(table, "master_id_int")
	n.Nickname = field.NewString(table, "nickname")
	n.PublishTime = field.NewString(table, "publish_time")
	n.PublishTimeMs = field.NewInt64(table, "publish_time_ms")
	n.ReplyID = field.NewString(table, "reply_id")
	n.ReplyIDInt = field.NewInt64(table, "reply_id_int")
	n.ResName = field.NewString(table, "res_name")
	n.Stars = field.NewString(table, "stars")
	n.StarsInt = field.NewInt64(table, "stars_int")
	n.UID = field.NewString(table, "uid")
	n.UIDInt = field.NewInt64(table, "uid_int")
	n.UserComment = field.NewString(table, "user_comment")

	n.fillFieldMap()

	return n
}

func (n *nePeProductCommentLog) WithContext(ctx context.Context) INePeProductCommentLogDo {
	return n.nePeProductCommentLogDo.WithContext(ctx)
}

func (n nePeProductCommentLog) TableName() string { return n.nePeProductCommentLogDo.TableName() }

func (n nePeProductCommentLog) Alias() string { return n.nePeProductCommentLogDo.Alias() }

func (n nePeProductCommentLog) Columns(cols ...field.Expr) gen.Columns {
	return n.nePeProductCommentLogDo.Columns(cols...)
}

func (n *nePeProductCommentLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nePeProductCommentLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 23)
	n.fieldMap["id"] = n.ID
	n.fieldMap["comment_id"] = n.CommentID
	n.fieldMap["comment_state"] = n.CommentState
	n.fieldMap["comment_tag"] = n.CommentTag
	n.fieldMap["commented_num"] = n.CommentedNum
	n.fieldMap["commented_num_int"] = n.CommentedNumInt
	n.fieldMap["good_num"] = n.GoodNum
	n.fieldMap["good_num_int"] = n.GoodNumInt
	n.fieldMap["iid"] = n.Iid
	n.fieldMap["iid_int"] = n.IidInt
	n.fieldMap["master_id"] = n.MasterID
	n.fieldMap["master_id_int"] = n.MasterIDInt
	n.fieldMap["nickname"] = n.Nickname
	n.fieldMap["publish_time"] = n.PublishTime
	n.fieldMap["publish_time_ms"] = n.PublishTimeMs
	n.fieldMap["reply_id"] = n.ReplyID
	n.fieldMap["reply_id_int"] = n.ReplyIDInt
	n.fieldMap["res_name"] = n.ResName
	n.fieldMap["stars"] = n.Stars
	n.fieldMap["stars_int"] = n.StarsInt
	n.fieldMap["uid"] = n.UID
	n.fieldMap["uid_int"] = n.UIDInt
	n.fieldMap["user_comment"] = n.UserComment
}

func (n nePeProductCommentLog) clone(db *gorm.DB) nePeProductCommentLog {
	n.nePeProductCommentLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nePeProductCommentLog) replaceDB(db *gorm.DB) nePeProductCommentLog {
	n.nePeProductCommentLogDo.ReplaceDB(db)
	return n
}

type nePeProductCommentLogDo struct{ gen.DO }

type INePeProductCommentLogDo interface {
	gen.SubQuery
	Debug() INePeProductCommentLogDo
	WithContext(ctx context.Context) INePeProductCommentLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INePeProductCommentLogDo
	WriteDB() INePeProductCommentLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INePeProductCommentLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INePeProductCommentLogDo
	Not(conds ...gen.Condition) INePeProductCommentLogDo
	Or(conds ...gen.Condition) INePeProductCommentLogDo
	Select(conds ...field.Expr) INePeProductCommentLogDo
	Where(conds ...gen.Condition) INePeProductCommentLogDo
	Order(conds ...field.Expr) INePeProductCommentLogDo
	Distinct(cols ...field.Expr) INePeProductCommentLogDo
	Omit(cols ...field.Expr) INePeProductCommentLogDo
	Join(table schema.Tabler, on ...field.Expr) INePeProductCommentLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductCommentLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INePeProductCommentLogDo
	Group(cols ...field.Expr) INePeProductCommentLogDo
	Having(conds ...gen.Condition) INePeProductCommentLogDo
	Limit(limit int) INePeProductCommentLogDo
	Offset(offset int) INePeProductCommentLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductCommentLogDo
	Unscoped() INePeProductCommentLogDo
	Create(values ...*model.NePeProductCommentLog) error
	CreateInBatches(values []*model.NePeProductCommentLog, batchSize int) error
	Save(values ...*model.NePeProductCommentLog) error
	First() (*model.NePeProductCommentLog, error)
	Take() (*model.NePeProductCommentLog, error)
	Last() (*model.NePeProductCommentLog, error)
	Find() ([]*model.NePeProductCommentLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductCommentLog, err error)
	FindInBatches(result *[]*model.NePeProductCommentLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NePeProductCommentLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INePeProductCommentLogDo
	Assign(attrs ...field.AssignExpr) INePeProductCommentLogDo
	Joins(fields ...field.RelationField) INePeProductCommentLogDo
	Preload(fields ...field.RelationField) INePeProductCommentLogDo
	FirstOrInit() (*model.NePeProductCommentLog, error)
	FirstOrCreate() (*model.NePeProductCommentLog, error)
	FindByPage(offset int, limit int) (result []*model.NePeProductCommentLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INePeProductCommentLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nePeProductCommentLogDo) Debug() INePeProductCommentLogDo {
	return n.withDO(n.DO.Debug())
}

func (n nePeProductCommentLogDo) WithContext(ctx context.Context) INePeProductCommentLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nePeProductCommentLogDo) ReadDB() INePeProductCommentLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n nePeProductCommentLogDo) WriteDB() INePeProductCommentLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n nePeProductCommentLogDo) Session(config *gorm.Session) INePeProductCommentLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n nePeProductCommentLogDo) Clauses(conds ...clause.Expression) INePeProductCommentLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nePeProductCommentLogDo) Returning(value interface{}, columns ...string) INePeProductCommentLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nePeProductCommentLogDo) Not(conds ...gen.Condition) INePeProductCommentLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nePeProductCommentLogDo) Or(conds ...gen.Condition) INePeProductCommentLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nePeProductCommentLogDo) Select(conds ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nePeProductCommentLogDo) Where(conds ...gen.Condition) INePeProductCommentLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nePeProductCommentLogDo) Order(conds ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nePeProductCommentLogDo) Distinct(cols ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nePeProductCommentLogDo) Omit(cols ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nePeProductCommentLogDo) Join(table schema.Tabler, on ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nePeProductCommentLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nePeProductCommentLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nePeProductCommentLogDo) Group(cols ...field.Expr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nePeProductCommentLogDo) Having(conds ...gen.Condition) INePeProductCommentLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nePeProductCommentLogDo) Limit(limit int) INePeProductCommentLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nePeProductCommentLogDo) Offset(offset int) INePeProductCommentLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nePeProductCommentLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductCommentLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nePeProductCommentLogDo) Unscoped() INePeProductCommentLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nePeProductCommentLogDo) Create(values ...*model.NePeProductCommentLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nePeProductCommentLogDo) CreateInBatches(values []*model.NePeProductCommentLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nePeProductCommentLogDo) Save(values ...*model.NePeProductCommentLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nePeProductCommentLogDo) First() (*model.NePeProductCommentLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductCommentLog), nil
	}
}

func (n nePeProductCommentLogDo) Take() (*model.NePeProductCommentLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductCommentLog), nil
	}
}

func (n nePeProductCommentLogDo) Last() (*model.NePeProductCommentLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductCommentLog), nil
	}
}

func (n nePeProductCommentLogDo) Find() ([]*model.NePeProductCommentLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NePeProductCommentLog), err
}

func (n nePeProductCommentLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductCommentLog, err error) {
	buf := make([]*model.NePeProductCommentLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nePeProductCommentLogDo) FindInBatches(result *[]*model.NePeProductCommentLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nePeProductCommentLogDo) Attrs(attrs ...field.AssignExpr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nePeProductCommentLogDo) Assign(attrs ...field.AssignExpr) INePeProductCommentLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nePeProductCommentLogDo) Joins(fields ...field.RelationField) INePeProductCommentLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nePeProductCommentLogDo) Preload(fields ...field.RelationField) INePeProductCommentLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nePeProductCommentLogDo) FirstOrInit() (*model.NePeProductCommentLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductCommentLog), nil
	}
}

func (n nePeProductCommentLogDo) FirstOrCreate() (*model.NePeProductCommentLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductCommentLog), nil
	}
}

func (n nePeProductCommentLogDo) FindByPage(offset int, limit int) (result []*model.NePeProductCommentLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nePeProductCommentLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nePeProductCommentLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nePeProductCommentLogDo) Delete(models ...*model.NePeProductCommentLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nePeProductCommentLogDo) withDO(do gen.Dao) *nePeProductCommentLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
