// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNePeProductFeedbackLog(db *gorm.DB, opts ...gen.DOOption) nePeProductFeedbackLog {
	_nePeProductFeedbackLog := nePeProductFeedbackLog{}

	_nePeProductFeedbackLog.nePeProductFeedbackLogDo.UseDB(db, opts...)
	_nePeProductFeedbackLog.nePeProductFeedbackLogDo.UseModel(&model.NePeProductFeedbackLog{})

	tableName := _nePeProductFeedbackLog.nePeProductFeedbackLogDo.TableName()
	_nePeProductFeedbackLog.ALL = field.NewAsterisk(tableName)
	_nePeProductFeedbackLog.ID = field.NewInt64(tableName, "id")
	_nePeProductFeedbackLog.FeedbackID = field.NewString(tableName, "feedback_id")
	_nePeProductFeedbackLog.CommitNickname = field.NewString(tableName, "commit_nickname")
	_nePeProductFeedbackLog.CommitUID = field.NewString(tableName, "commit_uid")
	_nePeProductFeedbackLog.CommitUIDInt = field.NewInt64(tableName, "commit_uid_int")
	_nePeProductFeedbackLog.Content = field.NewString(tableName, "content")
	_nePeProductFeedbackLog.CreateTimeMs = field.NewInt64(tableName, "create_time_ms")
	_nePeProductFeedbackLog.FeedbackLogFile = field.NewString(tableName, "feedback_log_file")
	_nePeProductFeedbackLog.ForbidReply = field.NewBool(tableName, "forbid_reply")
	_nePeProductFeedbackLog.HaveLogFile = field.NewBool(tableName, "have_log_file")
	_nePeProductFeedbackLog.Iid = field.NewString(tableName, "iid")
	_nePeProductFeedbackLog.IidInt = field.NewInt64(tableName, "iid_int")
	_nePeProductFeedbackLog.PicList = field.NewString(tableName, "pic_list")
	_nePeProductFeedbackLog.ResName = field.NewString(tableName, "res_name")
	_nePeProductFeedbackLog.Type = field.NewString(tableName, "type")

	_nePeProductFeedbackLog.fillFieldMap()

	return _nePeProductFeedbackLog
}

type nePeProductFeedbackLog struct {
	nePeProductFeedbackLogDo nePeProductFeedbackLogDo

	ALL             field.Asterisk
	ID              field.Int64
	FeedbackID      field.String
	CommitNickname  field.String
	CommitUID       field.String
	CommitUIDInt    field.Int64
	Content         field.String
	CreateTimeMs    field.Int64
	FeedbackLogFile field.String
	ForbidReply     field.Bool
	HaveLogFile     field.Bool
	Iid             field.String
	IidInt          field.Int64
	PicList         field.String
	ResName         field.String
	Type            field.String

	fieldMap map[string]field.Expr
}

func (n nePeProductFeedbackLog) Table(newTableName string) *nePeProductFeedbackLog {
	n.nePeProductFeedbackLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nePeProductFeedbackLog) As(alias string) *nePeProductFeedbackLog {
	n.nePeProductFeedbackLogDo.DO = *(n.nePeProductFeedbackLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nePeProductFeedbackLog) updateTableName(table string) *nePeProductFeedbackLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.FeedbackID = field.NewString(table, "feedback_id")
	n.CommitNickname = field.NewString(table, "commit_nickname")
	n.CommitUID = field.NewString(table, "commit_uid")
	n.CommitUIDInt = field.NewInt64(table, "commit_uid_int")
	n.Content = field.NewString(table, "content")
	n.CreateTimeMs = field.NewInt64(table, "create_time_ms")
	n.FeedbackLogFile = field.NewString(table, "feedback_log_file")
	n.ForbidReply = field.NewBool(table, "forbid_reply")
	n.HaveLogFile = field.NewBool(table, "have_log_file")
	n.Iid = field.NewString(table, "iid")
	n.IidInt = field.NewInt64(table, "iid_int")
	n.PicList = field.NewString(table, "pic_list")
	n.ResName = field.NewString(table, "res_name")
	n.Type = field.NewString(table, "type")

	n.fillFieldMap()

	return n
}

func (n *nePeProductFeedbackLog) WithContext(ctx context.Context) INePeProductFeedbackLogDo {
	return n.nePeProductFeedbackLogDo.WithContext(ctx)
}

func (n nePeProductFeedbackLog) TableName() string { return n.nePeProductFeedbackLogDo.TableName() }

func (n nePeProductFeedbackLog) Alias() string { return n.nePeProductFeedbackLogDo.Alias() }

func (n nePeProductFeedbackLog) Columns(cols ...field.Expr) gen.Columns {
	return n.nePeProductFeedbackLogDo.Columns(cols...)
}

func (n *nePeProductFeedbackLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nePeProductFeedbackLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 15)
	n.fieldMap["id"] = n.ID
	n.fieldMap["feedback_id"] = n.FeedbackID
	n.fieldMap["commit_nickname"] = n.CommitNickname
	n.fieldMap["commit_uid"] = n.CommitUID
	n.fieldMap["commit_uid_int"] = n.CommitUIDInt
	n.fieldMap["content"] = n.Content
	n.fieldMap["create_time_ms"] = n.CreateTimeMs
	n.fieldMap["feedback_log_file"] = n.FeedbackLogFile
	n.fieldMap["forbid_reply"] = n.ForbidReply
	n.fieldMap["have_log_file"] = n.HaveLogFile
	n.fieldMap["iid"] = n.Iid
	n.fieldMap["iid_int"] = n.IidInt
	n.fieldMap["pic_list"] = n.PicList
	n.fieldMap["res_name"] = n.ResName
	n.fieldMap["type"] = n.Type
}

func (n nePeProductFeedbackLog) clone(db *gorm.DB) nePeProductFeedbackLog {
	n.nePeProductFeedbackLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nePeProductFeedbackLog) replaceDB(db *gorm.DB) nePeProductFeedbackLog {
	n.nePeProductFeedbackLogDo.ReplaceDB(db)
	return n
}

type nePeProductFeedbackLogDo struct{ gen.DO }

type INePeProductFeedbackLogDo interface {
	gen.SubQuery
	Debug() INePeProductFeedbackLogDo
	WithContext(ctx context.Context) INePeProductFeedbackLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INePeProductFeedbackLogDo
	WriteDB() INePeProductFeedbackLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INePeProductFeedbackLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INePeProductFeedbackLogDo
	Not(conds ...gen.Condition) INePeProductFeedbackLogDo
	Or(conds ...gen.Condition) INePeProductFeedbackLogDo
	Select(conds ...field.Expr) INePeProductFeedbackLogDo
	Where(conds ...gen.Condition) INePeProductFeedbackLogDo
	Order(conds ...field.Expr) INePeProductFeedbackLogDo
	Distinct(cols ...field.Expr) INePeProductFeedbackLogDo
	Omit(cols ...field.Expr) INePeProductFeedbackLogDo
	Join(table schema.Tabler, on ...field.Expr) INePeProductFeedbackLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductFeedbackLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INePeProductFeedbackLogDo
	Group(cols ...field.Expr) INePeProductFeedbackLogDo
	Having(conds ...gen.Condition) INePeProductFeedbackLogDo
	Limit(limit int) INePeProductFeedbackLogDo
	Offset(offset int) INePeProductFeedbackLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductFeedbackLogDo
	Unscoped() INePeProductFeedbackLogDo
	Create(values ...*model.NePeProductFeedbackLog) error
	CreateInBatches(values []*model.NePeProductFeedbackLog, batchSize int) error
	Save(values ...*model.NePeProductFeedbackLog) error
	First() (*model.NePeProductFeedbackLog, error)
	Take() (*model.NePeProductFeedbackLog, error)
	Last() (*model.NePeProductFeedbackLog, error)
	Find() ([]*model.NePeProductFeedbackLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductFeedbackLog, err error)
	FindInBatches(result *[]*model.NePeProductFeedbackLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NePeProductFeedbackLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INePeProductFeedbackLogDo
	Assign(attrs ...field.AssignExpr) INePeProductFeedbackLogDo
	Joins(fields ...field.RelationField) INePeProductFeedbackLogDo
	Preload(fields ...field.RelationField) INePeProductFeedbackLogDo
	FirstOrInit() (*model.NePeProductFeedbackLog, error)
	FirstOrCreate() (*model.NePeProductFeedbackLog, error)
	FindByPage(offset int, limit int) (result []*model.NePeProductFeedbackLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INePeProductFeedbackLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nePeProductFeedbackLogDo) Debug() INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Debug())
}

func (n nePeProductFeedbackLogDo) WithContext(ctx context.Context) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nePeProductFeedbackLogDo) ReadDB() INePeProductFeedbackLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n nePeProductFeedbackLogDo) WriteDB() INePeProductFeedbackLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n nePeProductFeedbackLogDo) Session(config *gorm.Session) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n nePeProductFeedbackLogDo) Clauses(conds ...clause.Expression) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nePeProductFeedbackLogDo) Returning(value interface{}, columns ...string) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nePeProductFeedbackLogDo) Not(conds ...gen.Condition) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nePeProductFeedbackLogDo) Or(conds ...gen.Condition) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nePeProductFeedbackLogDo) Select(conds ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nePeProductFeedbackLogDo) Where(conds ...gen.Condition) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nePeProductFeedbackLogDo) Order(conds ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nePeProductFeedbackLogDo) Distinct(cols ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nePeProductFeedbackLogDo) Omit(cols ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nePeProductFeedbackLogDo) Join(table schema.Tabler, on ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nePeProductFeedbackLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nePeProductFeedbackLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nePeProductFeedbackLogDo) Group(cols ...field.Expr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nePeProductFeedbackLogDo) Having(conds ...gen.Condition) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nePeProductFeedbackLogDo) Limit(limit int) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nePeProductFeedbackLogDo) Offset(offset int) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nePeProductFeedbackLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nePeProductFeedbackLogDo) Unscoped() INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nePeProductFeedbackLogDo) Create(values ...*model.NePeProductFeedbackLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nePeProductFeedbackLogDo) CreateInBatches(values []*model.NePeProductFeedbackLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nePeProductFeedbackLogDo) Save(values ...*model.NePeProductFeedbackLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nePeProductFeedbackLogDo) First() (*model.NePeProductFeedbackLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductFeedbackLog), nil
	}
}

func (n nePeProductFeedbackLogDo) Take() (*model.NePeProductFeedbackLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductFeedbackLog), nil
	}
}

func (n nePeProductFeedbackLogDo) Last() (*model.NePeProductFeedbackLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductFeedbackLog), nil
	}
}

func (n nePeProductFeedbackLogDo) Find() ([]*model.NePeProductFeedbackLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NePeProductFeedbackLog), err
}

func (n nePeProductFeedbackLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NePeProductFeedbackLog, err error) {
	buf := make([]*model.NePeProductFeedbackLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nePeProductFeedbackLogDo) FindInBatches(result *[]*model.NePeProductFeedbackLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nePeProductFeedbackLogDo) Attrs(attrs ...field.AssignExpr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nePeProductFeedbackLogDo) Assign(attrs ...field.AssignExpr) INePeProductFeedbackLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nePeProductFeedbackLogDo) Joins(fields ...field.RelationField) INePeProductFeedbackLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nePeProductFeedbackLogDo) Preload(fields ...field.RelationField) INePeProductFeedbackLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nePeProductFeedbackLogDo) FirstOrInit() (*model.NePeProductFeedbackLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductFeedbackLog), nil
	}
}

func (n nePeProductFeedbackLogDo) FirstOrCreate() (*model.NePeProductFeedbackLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NePeProductFeedbackLog), nil
	}
}

func (n nePeProductFeedbackLogDo) FindByPage(offset int, limit int) (result []*model.NePeProductFeedbackLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nePeProductFeedbackLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nePeProductFeedbackLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nePeProductFeedbackLogDo) Delete(models ...*model.NePeProductFeedbackLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nePeProductFeedbackLogDo) withDO(do gen.Dao) *nePeProductFeedbackLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
