// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/taixue-cn/com-stats/internal/pkg/infra/rds/model"
)

func newNeUserLog(db *gorm.DB, opts ...gen.DOOption) neUserLog {
	_neUserLog := neUserLog{}

	_neUserLog.neUserLogDo.UseDB(db, opts...)
	_neUserLog.neUserLogDo.UseModel(&model.NeUserLog{})

	tableName := _neUserLog.neUserLogDo.TableName()
	_neUserLog.ALL = field.NewAsterisk(tableName)
	_neUserLog.ID = field.NewInt64(tableName, "id")
	_neUserLog.NeLogID = field.NewInt64(tableName, "ne_log_id")
	_neUserLog.UserID = field.NewString(tableName, "user_id")
	_neUserLog.PeProductsPayload = field.NewString(tableName, "pe_products_payload")
	_neUserLog.PeProductCommentLogsPayload = field.NewString(tableName, "pe_product_comment_logs_payload")
	_neUserLog.PeProductFeedbackLogsPayload = field.NewString(tableName, "pe_product_feedback_logs_payload")
	_neUserLog.CompProductLogsPayload = field.NewString(tableName, "comp_product_logs_payload")

	_neUserLog.fillFieldMap()

	return _neUserLog
}

type neUserLog struct {
	neUserLogDo neUserLogDo

	ALL                          field.Asterisk
	ID                           field.Int64
	NeLogID                      field.Int64
	UserID                       field.String
	PeProductsPayload            field.String
	PeProductCommentLogsPayload  field.String
	PeProductFeedbackLogsPayload field.String
	CompProductLogsPayload       field.String

	fieldMap map[string]field.Expr
}

func (n neUserLog) Table(newTableName string) *neUserLog {
	n.neUserLogDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n neUserLog) As(alias string) *neUserLog {
	n.neUserLogDo.DO = *(n.neUserLogDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *neUserLog) updateTableName(table string) *neUserLog {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NeLogID = field.NewInt64(table, "ne_log_id")
	n.UserID = field.NewString(table, "user_id")
	n.PeProductsPayload = field.NewString(table, "pe_products_payload")
	n.PeProductCommentLogsPayload = field.NewString(table, "pe_product_comment_logs_payload")
	n.PeProductFeedbackLogsPayload = field.NewString(table, "pe_product_feedback_logs_payload")
	n.CompProductLogsPayload = field.NewString(table, "comp_product_logs_payload")

	n.fillFieldMap()

	return n
}

func (n *neUserLog) WithContext(ctx context.Context) INeUserLogDo {
	return n.neUserLogDo.WithContext(ctx)
}

func (n neUserLog) TableName() string { return n.neUserLogDo.TableName() }

func (n neUserLog) Alias() string { return n.neUserLogDo.Alias() }

func (n neUserLog) Columns(cols ...field.Expr) gen.Columns { return n.neUserLogDo.Columns(cols...) }

func (n *neUserLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *neUserLog) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 7)
	n.fieldMap["id"] = n.ID
	n.fieldMap["ne_log_id"] = n.NeLogID
	n.fieldMap["user_id"] = n.UserID
	n.fieldMap["pe_products_payload"] = n.PeProductsPayload
	n.fieldMap["pe_product_comment_logs_payload"] = n.PeProductCommentLogsPayload
	n.fieldMap["pe_product_feedback_logs_payload"] = n.PeProductFeedbackLogsPayload
	n.fieldMap["comp_product_logs_payload"] = n.CompProductLogsPayload
}

func (n neUserLog) clone(db *gorm.DB) neUserLog {
	n.neUserLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n neUserLog) replaceDB(db *gorm.DB) neUserLog {
	n.neUserLogDo.ReplaceDB(db)
	return n
}

type neUserLogDo struct{ gen.DO }

type INeUserLogDo interface {
	gen.SubQuery
	Debug() INeUserLogDo
	WithContext(ctx context.Context) INeUserLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INeUserLogDo
	WriteDB() INeUserLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INeUserLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INeUserLogDo
	Not(conds ...gen.Condition) INeUserLogDo
	Or(conds ...gen.Condition) INeUserLogDo
	Select(conds ...field.Expr) INeUserLogDo
	Where(conds ...gen.Condition) INeUserLogDo
	Order(conds ...field.Expr) INeUserLogDo
	Distinct(cols ...field.Expr) INeUserLogDo
	Omit(cols ...field.Expr) INeUserLogDo
	Join(table schema.Tabler, on ...field.Expr) INeUserLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INeUserLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) INeUserLogDo
	Group(cols ...field.Expr) INeUserLogDo
	Having(conds ...gen.Condition) INeUserLogDo
	Limit(limit int) INeUserLogDo
	Offset(offset int) INeUserLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INeUserLogDo
	Unscoped() INeUserLogDo
	Create(values ...*model.NeUserLog) error
	CreateInBatches(values []*model.NeUserLog, batchSize int) error
	Save(values ...*model.NeUserLog) error
	First() (*model.NeUserLog, error)
	Take() (*model.NeUserLog, error)
	Last() (*model.NeUserLog, error)
	Find() ([]*model.NeUserLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NeUserLog, err error)
	FindInBatches(result *[]*model.NeUserLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NeUserLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INeUserLogDo
	Assign(attrs ...field.AssignExpr) INeUserLogDo
	Joins(fields ...field.RelationField) INeUserLogDo
	Preload(fields ...field.RelationField) INeUserLogDo
	FirstOrInit() (*model.NeUserLog, error)
	FirstOrCreate() (*model.NeUserLog, error)
	FindByPage(offset int, limit int) (result []*model.NeUserLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INeUserLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n neUserLogDo) Debug() INeUserLogDo {
	return n.withDO(n.DO.Debug())
}

func (n neUserLogDo) WithContext(ctx context.Context) INeUserLogDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n neUserLogDo) ReadDB() INeUserLogDo {
	return n.Clauses(dbresolver.Read)
}

func (n neUserLogDo) WriteDB() INeUserLogDo {
	return n.Clauses(dbresolver.Write)
}

func (n neUserLogDo) Session(config *gorm.Session) INeUserLogDo {
	return n.withDO(n.DO.Session(config))
}

func (n neUserLogDo) Clauses(conds ...clause.Expression) INeUserLogDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n neUserLogDo) Returning(value interface{}, columns ...string) INeUserLogDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n neUserLogDo) Not(conds ...gen.Condition) INeUserLogDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n neUserLogDo) Or(conds ...gen.Condition) INeUserLogDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n neUserLogDo) Select(conds ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n neUserLogDo) Where(conds ...gen.Condition) INeUserLogDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n neUserLogDo) Order(conds ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n neUserLogDo) Distinct(cols ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n neUserLogDo) Omit(cols ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n neUserLogDo) Join(table schema.Tabler, on ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n neUserLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n neUserLogDo) RightJoin(table schema.Tabler, on ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n neUserLogDo) Group(cols ...field.Expr) INeUserLogDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n neUserLogDo) Having(conds ...gen.Condition) INeUserLogDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n neUserLogDo) Limit(limit int) INeUserLogDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n neUserLogDo) Offset(offset int) INeUserLogDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n neUserLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INeUserLogDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n neUserLogDo) Unscoped() INeUserLogDo {
	return n.withDO(n.DO.Unscoped())
}

func (n neUserLogDo) Create(values ...*model.NeUserLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n neUserLogDo) CreateInBatches(values []*model.NeUserLog, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n neUserLogDo) Save(values ...*model.NeUserLog) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n neUserLogDo) First() (*model.NeUserLog, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeUserLog), nil
	}
}

func (n neUserLogDo) Take() (*model.NeUserLog, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeUserLog), nil
	}
}

func (n neUserLogDo) Last() (*model.NeUserLog, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeUserLog), nil
	}
}

func (n neUserLogDo) Find() ([]*model.NeUserLog, error) {
	result, err := n.DO.Find()
	return result.([]*model.NeUserLog), err
}

func (n neUserLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NeUserLog, err error) {
	buf := make([]*model.NeUserLog, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n neUserLogDo) FindInBatches(result *[]*model.NeUserLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n neUserLogDo) Attrs(attrs ...field.AssignExpr) INeUserLogDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n neUserLogDo) Assign(attrs ...field.AssignExpr) INeUserLogDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n neUserLogDo) Joins(fields ...field.RelationField) INeUserLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n neUserLogDo) Preload(fields ...field.RelationField) INeUserLogDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n neUserLogDo) FirstOrInit() (*model.NeUserLog, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeUserLog), nil
	}
}

func (n neUserLogDo) FirstOrCreate() (*model.NeUserLog, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NeUserLog), nil
	}
}

func (n neUserLogDo) FindByPage(offset int, limit int) (result []*model.NeUserLog, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n neUserLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n neUserLogDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n neUserLogDo) Delete(models ...*model.NeUserLog) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *neUserLogDo) withDO(do gen.Dao) *neUserLogDo {
	n.DO = *do.(*gen.DO)
	return n
}
