name: Schem Render Service Build & Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./idunn-renderer-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'npm'
          cache-dependency-path: './idunn-renderer-service/package-lock.json'

      - run: npm install

      # --- 修改点开始 ---
      - name: Build Project
        # 在这里注入环境变量，Vite 会在构建时将其写入代码
        # env:
        #   VITE_API_URL: https://idunn.taixue.cc
        run: npm run build
      # --- 修改点结束 ---

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: idunn-renderer-service

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Files
        # 请确保 frontend/build/client/ 这个路径是正确的
        # 如果你的 vite 配置输出目录是 dist，这里可能需要改为 build/dist/ 或者直接 dist/
        run: rsync -avz --delete -e "ssh -p ${{ secrets.SSH_PORT }}" package.json dist public src index.html server.js ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/taixue/data/services/idunn-renderer-service/build/src
